#!/bin/ksh

YEAR=$(date "+%Y")
STAGING=/var/tmp/staging
SPLUNK=/opt/splunk
ARCHIVE=/ELI/archive
node_=$(hostname)
#Using .zip file with hostname + fqdn
hostname_fqdn=$(host $(uname -n)|awk '{print $1}')
splunk_version=`rpm -q splunk|awk -F- '{print $2}'`
env_=`uname -n|grep -o '...$'`

case ${env_} in
   pdv | bdv ) uid=svc_act2
               gid=unx_60231_splunk_admin_dev
               ;;
   some_loc | loc2 ) uid=svc_act1
               gid=unx_9998_access
               ;;
esac

usage() {

cat<<++
Invalid Option!!!
USAGE:  $0 RELEASE_ID | CRQ#

  where
        RELEASE_ID = i.e. -> 20140114A
        CRQ# Change Request Number

++

}

[[ -z $1 ]] && {
  usage
  exit 1
}

cd ${SPLUNK} && {
      echo "Backup Splunk config files to /opt/splunk/splunk-${splunk_version}-etc-${1}.zip"
      echo "zip -qr splunk-${splunk_version}-etc-${1}.zip etc/*"
      zip -qr splunk-${splunk_version}-etc-${1}.zip etc/*
      chown ${uid}:${gid} splunk-${splunk_version}-etc-${1}.zip
      ls -l splunk-${splunk_version}-etc-${1}.zip
      echo "Done."
}
