#!/bin/ksh
echo "PROCESS      PID    SWAP"
echo "-------      ------ -------"
{
for file in /proc/*/status
do
 [[ -f $file ]] && {
 awk '/^Pid|VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file
 }
done
}|grep kB | grep -wv "0 kB" | sort -k 3 -n -r | column -t

