#!/bin/ksh
# The script shows how-to resync stale KV store members
# Based on
# https://docs.splunk.com/Documentation/Splunk/7.0.3/Admin/ResyncKVstore
#

[[ "`whoami`" != "svc_act1" ]] && {
  echo "This script runs as svc_act1 only. Abort."
  exit
}

captain=`/opt/splunk/bin/splunk list shcluster-members -auth admin:$(uname -n)_admin|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}'`

replicationStatus=`/opt/splunk/bin/splunk show kvstore-status -auth admin:$(uname -n)_admin|grep replicationStatus | egrep -v 'Non-captain KV store member|KV store captain'`
[[ -n $replicationStatus ]] && {
  echo replicationStatus=$replicationStatus
  echo
  echo "stale KV store. Run the following on Search Head Captain: $captain"
  echo "/opt/splunk/bin/splunk resync kvstore"
  echo
  echo "To verify,"
  echo "opt/splunk/bin/splunk show kvstore-status"
  echo
  cat<<END

 If fewer than half of the members are stale, resync each member individually.

 1. Stop the search head that has the stale KV store member.
 2. Run the command, /opt/splunk/bin/splunk clean kvstore --local
 3. Restart the search head. This triggers the initial synchronization from other KV store members.
 4. Run the command, /opt/splunk/bin/splunk show kvstore-status, to verify synchronization.

END
}

