#!/bin/bash
 
SPLUNK_HOME=/opt/splunk
OUTPUT_DIR=/var/tmp/splunk_pstacks
SAMPLES=300
SAMPLE_PERIOD=2

[[ -d $OUTPUT_DIR ]] && rm -f $OUTPUT_DIR/pstack_splunkd*.out
[[ ! -d $OUTPUT_DIR ]] && mkdir $OUTPUT_DIR

echo -n "How many samples you wish to gather (100-300)? "
read SAMPLES
echo -n "Let me know the interval 1-10 seconds? "
read SAMPLE_PERIOD
 
i=0
while [ $i -lt $SAMPLES ]
do
    pstack `head -1 $SPLUNK_HOME/var/run/splunk/splunkd.pid` > $OUTPUT_DIR/pstack_splunkd-$i-`date +%s`.out
    let "i+=1"
    echo -n "$i "
    sleep $SAMPLE_PERIOD
done
echo 
echo "Done"
echo "OUTPUTS: $OUTPUT_DIR/pstack_splunkd-[0-$(($i-1))]-`date +%s`.out"
echo
