#!/bin/bash
#########################################################################
#
#  Generates /etc/motd from the following standard files plus optionals.
#  Installed via RPM on linux with Standard motd pieces and /etc/issue.
#  If the command is run without options and the file 
#  /etc/genban.d/cur.state exists with the first line being prod, imp, or
#  dev then it will generate the motd using that as the command option.
#  The -c option will generate the cur.state file in /etc/motd.d with 
#  whatever the following option is before executing the motd build.
#
#  Standard
#  /etc/genban.d/motd.<accept|dead|dev|imp|pprod|prod|qa|sand|test>
#  /etc/redhat-release
#
#  Optionals
#  /etc/genban.d/motd.##
#  
#  Format:
#  genban [-c|m|r] [accept|dead|dev|imp|pprod|prod|qa|sand|test]
#
#  Choose according to status of server: production, implementation, or
#  development.  Optionals allow later features and /etc/motd
#  customizations specific to individual servers.  The lowest . numbers
#  get added first after the Standard files.  i.e. motd.00 is added
#  before motd.01.  Do not use mord.99 as it is reserved for the
#  -r option.
#
########################################################################

##  Redirect stderr to the bit bucket.

exec 2> /dev/null

USAGE="genban [-c|m|r] [accept|dead|dev|imp|pprod|prod|qa|sand|test]"
##  Check for correct usage and parse options.

case $1 in
"")
  if [ -f /etc/genban.d/cur.state ]; then
    OPT=`head -1 /etc/genban.d/cur.state`
  else
    echo "/etc/genban.d/cur.state must be populated and exist for no options use."
    echo $USAGE
    exit 1
  fi;;

-c)
  if [ -n "$2" ]; then
    echo $2 > /etc/genban.d/cur.state
    OPT=$2
  else
    echo $USAGE
    exit 1
  fi;;

-m)
  if [ -n "$2" ]; then
    OPT=$2
    cat /etc/genban.d/motd.maint > /etc/genban.d/motd.99
  else
    if [ -f /etc/genban.d/cur.state ]; then
      OPT=`head -1 /etc/genban.d/cur.state`
      cat /etc/genban.d/motd.maint > /etc/genban.d/motd.99
    else
      echo $USAGE
      exit 1
    fi
  fi;;

-r)
  if [ -n "$2" ]; then
    OPT=$2
    rm /etc/genban.d/motd.99
  else
    if [ -f /etc/genban.d/cur.state ]; then
      OPT=`head -1 /etc/genban.d/cur.state`
      rm /etc/genban.d/motd.99
    else
      echo "/etc/gneban.d/cur.state must be populated and exist for no options use."
      echo $USAGE
      exit 1
    fi
  fi;;
*)
  OPT=$1;;
esac

###  Cat standard files into /etc/genban.d/motd.tmp before replacing.

case $OPT in
accept)
  if [ -f /etc/genban.d/motd.accept ]; then
    cat /etc/genban.d/motd.accept > /etc/genban.d/motd.tmp
  fi;;

dev)
  if [ -f /etc/genban.d/motd.dev ]; then
    cat /etc/genban.d/motd.dev > /etc/genban.d/motd.tmp
  fi;;

dead)
  if [ -f /etc/genban.d/motd.dead ]; then
    cat /etc/genban.d/motd.dead > /etc/genban.d/motd.tmp
  fi;;

imp)
  if [ -f /etc/genban.d/motd.imp ]; then
    cat /etc/genban.d/motd.imp > /etc/genban.d/motd.tmp
  fi;;

pprod)
  if [ -f /etc/genban.d/motd.pprod ]; then
    cat /etc/genban.d/motd.pprod > /etc/genban.d/motd.tmp
  fi;;

prod)
  if [ -f /etc/genban.d/motd.prod ]; then
    cat /etc/genban.d/motd.prod > /etc/genban.d/motd.tmp
  fi;;

qa)
  if [ -f /etc/genban.d/motd.qa ]; then
    cat /etc/genban.d/motd.qa > /etc/genban.d/motd.tmp
  fi;;

sand)
  if [ -f /etc/genban.d/motd.sand ]; then
    cat /etc/genban.d/motd.sand > /etc/genban.d/motd.tmp
  fi;;

test)
  if [ -f /etc/genban.d/motd.test ]; then
    cat /etc/genban.d/motd.test > /etc/genban.d/motd.tmp
  fi;;

*)
  echo "Syntax error"
  echo $USAGE
  exit 1;;

esac

if [ `uname -a|cut -d" " -f1` == "Linux" ]; then
  if [ `uname -i|cut -d_ -f2` == "64" ]; then
    echo "`cat /etc/redhat-release` 64-bit" >> /etc/genban.d/motd.tmp
    echo " " >> /etc/genban.d/motd.tmp
  else
    cat /etc/redhat-release >> /etc/genban.d/motd.tmp

    echo " " >> /etc/genban.d/motd.tmp
  fi
fi

###  Add all custom motd.## files to the build.

for i in `ls /etc/genban.d/motd.[0-9][0-9]`
do
  cat $i >> /etc/genban.d/motd.tmp
done

###  Backup existing motd and replace

cp -p /etc/motd /etc/motd.`date +%m%d%Y`
echo "/etc/motd backed up to /etc/motd.`date +%m%d%Y`"
mv /etc/genban.d/motd.tmp /etc/motd

exit 0
