#!/bin/bash
################################################################################
# https://jiradomain1/browse/TOS-19015
# https://docs.splunk.com/Documentation/Splunk/9.0.4/Admin/BackupKVstore
# This script performs the following tasks:
# 1. In ${KVSTORE_BACKUP}, identify all file older than 3 days then move them
#    to ${KVSTORE_ARCHIVE}
# 2. In ${KVSTORE_ARCHIVE}, clean up files older than 3 days which came from
#    1. in previous days.
################################################################################
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
date_=$(date '+%a%H%M_%m%d%Y')
KVSTORE_BACKUP=/opt/splunkindex_data/kvstorebackup
KVSTORE_ARCHIVE=${KVSTORE_BACKUP}/kvstore_ARCHIVE
KVSTORE_LOG=/var/tmp/LOG/Kvstore

case ${env_} in
   pdv | bdv ) uid=svc_act2
               key=$dev
               ;;
   some_loc | loc2 | loc3 | loc4 ) uid=svc_act1
               key=$prod
               ;;
           * )
               case `uname -n` in
                   some_loc1* ) uid=svc_act1
                           gid=unx_9998_access
                           key=$prod
                           ;;
                   cud*| cut* ) uid=svc_act2
                                  gid=unx_60231_splunk_admin_dev
                                  key=$dev
                           ;;
               esac
               ;;
esac


[[ ! -d ${KVSTORE_ARCHIVE} ]] && mkdir -p ${KVSTORE_ARCHIVE}
[[ "$(whoami)" = "root" ]] && echo "Run as ${uid} ONLY. Abort" && exit
{
  # 1.
  date
  echo "1. Moving recent kvstore backups to ${KVSTORE_ARCHIVE}:"
  cd ${KVSTORE_BACKUP} && {
     # generate a list of files > 3 days
     file_list=$(find . -maxdepth 1 -type f -name "$(uname -n)*" ! -mmin -4320 -exec ls -d {} + )
     if [[ ! -z "${file_list}" ]]
     then
        echo "${KVSTORE_BACKUP}, below are files older than 3 days:"
        echo
        echo "${file_list}"
        echo "Moving above to ${KVSTORE_ARCHIVE}"
        find ${file_list} |cpio -pd ${KVSTORE_ARCHIVE} >/dev/null
        [[ "$?" = "0" ]] && find ${file_list} -maxdepth 1 -type f ! -mmin -4320 -exec rm -f {} +
        echo "1. COMPLETED."
     else
        echo "No file to move to ${KVSTORE_ARCHIVE}"
     fi
  }

  # 2.
  echo
  date
  echo "2. Cleaning up old kvstore backups in ${KVSTORE_ARCHIVE}"
  cd ${KVSTORE_ARCHIVE} && {
    find . -type d -name "kvstore_ARCHIVE" -exec rm -rf {} +
    # generate a list of files > 3 days
    file_list=$(find . -type f -name "*$(uname -n)*" ! -mmin -4320 -exec ls -d {} + )

    if [[ ! -z "${file_list}" ]]
    then
       echo "${KVSTORE_ARCHIVE}, below are files older than 3 days will be removed:"
       echo "${file_list}"
       echo
       find ${file_list} ! -mmin -4320 -exec rm -f {} +
       echo "2. COMPLETED."
    else
       echo "NONE FOUND"
    fi
  }
  date
} | tee ${KVSTORE_LOG}/`basename $0`_${date_}.log
