#!/bin/ksh
env_=`uname -n|grep -o '...$'`

case ${env_} in
   pdv | bdv ) uid=svc_act2
               gid=unx_60231_splunk_admin_dev
               ;;
   some_loc | loc2 ) uid=svc_act1
               gid=unx_9998_access
               ;;
esac

{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
captain=`su - ${uid} -c "/opt/splunk/bin/splunk list shcluster-members -auth admin:${prod}|grep -A1 'is_captain:1'|tail -1"|awk -F: '{print $2}'`
echo "$captain"
