#!/bin/ksh
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`

{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
case ${env_} in
   pdv | bdv ) uid=svc_act2
               key=$dev
               ;;
   some_loc | loc2 | loc3 ) uid=svc_act1
               key=$prod
               ;;
           * )
               case `uname -n` in
                   some_loc1* ) uid=svc_act1
                           gid=unx_9998_access
                           key=$prod
                           ;;
                   cud*| cut* ) uid=svc_act2
                                  gid=unx_60231_splunk_admin_dev
                                  key=$dev
                           ;;
               esac
               ;;
esac

su - ${uid} -c "echo '------------------------';${SPLUNK_BIN}/splunk login -auth admin:$key;${SPLUNK_BIN}/splunk show kvstore-status|grep -B2 'status'|grep -v 'standalone'|sed 's/[[:space:]]//g'"
