#!/bin/bash
#############################################################################
# This script is to point Splunk Search Head or Search Head Cluster to 
# additional Index Cluster Master (CM). 
# - If a Search Head is at PDC1/3, point to splunkmasternode-loc5.mycorp.com
# - If a Search Head is at DC4, point to splunkmasternode.mycorp.com
# Script's based on 
# https://docs.splunk.com/Documentation/Splunk/8.0.1/Indexer/Configuremulti-clustersearch
# Note: 
# Once server.conf updated,
# - If standalone Search Head, restart splunk.
# - If Search Head Cluster, perform rolling restart.
# - To verify, on https://splunk-preprod.mycorp.com, run
#   index=_internal | stats count by splunk_server
# Should see 120 Indexers@PDC1/3 and 20 Indexers@DC4.
#############################################################################
# Written By user1 P. user1 | Team
SERVER_CONF=/opt/splunk/etc/system/local/server.conf
date_=`date '+%Y%m%d'`
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
{
eval `gpg --batch --xyz xyz -quiet --no-verbose -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               key=$dev
               ;;
   some_loc | loc2 | loc3 ) uid=ser_act.prod
               key=$prod
               ;;
           * )
               case `uname -n` in
                   ser2* ) uid=ser_act.prod
                           gid=unx_9998_access
                           key=$prod
                           ;;
                   cud*| cut* ) uid=ser_act.dev
                                  gid=unx_60231_splunk_admin_dev
                                  key=$dev
                           ;;
               esac
               ;;
esac
# Backup $SERVER_CONF
cp -f ${SERVER_CONF} ${SERVER_CONF}.${date_}
chown ${uid}:${gid} ${SERVER_CONF}.${date_}


cat<<END >> ${SERVER_CONF}

[clustering]
mode = searchhead
master_uri = clustermaster:PDC1, clustermaster:DC4, clustermaster:CD1_A

[clustermaster:PDC1]
master_uri = https://splunkmasternode.mycorp.com:8089
mode = searchhead
multisite = true
pass4SymmKey = prodcluster 


[clustermaster:DC4]
master_uri = https://splunkmasternode-loc5.mycorp.com:8089
mode = searchhead
multisite = true
pass4SymmKey = prodcluster-loc5 

[clustermaster:CD1_A]
master_uri = https://ser27-005833.us.global.mycorp.com:8089
mode = searchhead
multisite = true
pass4SymmKey = prodcluster_1-loc44 

END

