#!/bin/ksh
# NOTE:
# Once script ran, it will copy /opt/splunk/etc/auth/distServerKeys/trusted.pem
# to remote host in
# PDC1_Indexers:/opt/splunk/etc/auth/distServerKeys/`uname -n`/trusted.pem
#
PDC1_Indexers="s02151some_loc
s02152some_loc
s02153some_loc
s02154some_loc
s02155some_loc
s02156some_loc
s02157some_loc
s02158some_loc
s02159some_loc
s02160some_loc
s02161some_loc
s02162some_loc
s02163some_loc
s02164some_loc
s02165some_loc
s02166some_loc
s02167some_loc
s02168some_loc
s02169some_loc
s02170some_loc
s02171some_loc
s02172some_loc
s02173some_loc
s02174some_loc
s02175some_loc
s0338some_loc
s0339some_loc
s0340some_loc
s0341some_loc
s0342some_loc
s0343some_loc
s0344some_loc
s0345some_loc
s0346some_loc
s0347some_loc"


local_distsearch="/opt/splunk/etc/system/local/distsearch.conf"

if [ -f ${local_distsearch} ]
then
   current_=`grep '^servers' ${local_distsearch}|sed -e 's/servers=//g' -e 's/servers = //g' -e 's/.some_loc.mycorp.com//g' -e 's/,/ /g' -e 's/:8089//g'`
else
   current_=""
fi

echo "Update $local_distsearch "
for x in ${PDC1_Indexers}
do
  if [ $x == $(uname -n) ]; then
    echo "skipping $x..."
  else
    echo ${current_}|  grep "$x"  >/dev/null
    case $? in
       0 )
           echo "Skipping $x..."
           ;;
       *)
         echo "Adding $x "
         #echo '/opt/splunk/bin/splunk login -auth admin:mycorp'
#        echo "/opt/splunk/bin/splunk add search-server -host ${x}:8089 -auth admin:`uname -n`_admin -remoteUsername admin -remotePassword ${x}_admin"
         /opt/splunk/bin/splunk add search-server -host ${x}:8089 -auth admin:`uname -n`_admin -remoteUsername admin -remotePassword ${x}_admin
           ;;
    esac
  fi
done
