#!/bin/ksh


cd /opt/splunk/etc/system/local && {
   cp -f server.conf server.conf.08152022
   {
     cat server.conf
     cat <<END

[httpServer]
maxThreads=100000
maxSockets=50000

END
   } > server.conf.STAGE
   chown ser_act.prod:unx_9998_access server.conf.STAGE server.conf.08152022

}
