#!/bin/bash
# This script will update Search Head ${SPLUNK_LOCAL}/server.conf
# CRQ000001272705 scheduled 3/22/2023
# 1. Append , clustermaster:CD1_C to
#    master_uri = clustermaster:PDC1, clustermaster:DC4, clustermaster:CD1_A, clustermaster:CD1_B
#
# 2. Add the following stanza 
# < [clustermaster:CD1_C]
# < master_uri = https://ser27-005850.us.global.mycorp.com:8089
# < mode = searchhead
# < multisite = true
# < pass4SymmKey = prodcluster_3-loc44
# <
#
SPLUNK_LOCAL=/opt/splunk/etc/system/local
#SPLUNK_TMP=/tmp
date_=$(date '+%m%d%Y')
cd ${SPLUNK_LOCAL} && {
#cd ${SPLUNK_TMP} && {
   [[ -f server.conf ]] && \
   sed -i.${date_} -e '1,/master_uri = clustermaster:PDC1, clustermaster:DC4, clustermaster:CD1_A, clustermaster:CD1_B/s/master_uri = clustermaster:PDC1, clustermaster:DC4, clustermaster:CD1_A, clustermaster:CD1_B/master_uri = clustermaster:PDC1, clustermaster:DC4, clustermaster:CD1_A, clustermaster:CD1_B, clustermaster:CD1_C/' -e '$ a\[clustermaster:CD1_C\]\nmaster_uri = https:\/\/ser27-005850.us.global.mycorp.com:8089\nmode = searchhead\nmultisite = true\npass4SymmKey = prodcluster_3-loc44\n' server.conf

   chown ser_act.prod:unx_9998_access server.conf server.conf.${date_}
}
