#!/bin/ksh

cd /etc && {
  grep '^vm.swappiness = 5' sysctl.conf >/dev/null
  [[ "$?" = "0" ]] && {
    echo "Swappiness already implemented."
    grep 'vm.swappiness = 5' sysctl.conf
    exit
  }
  #echo -n "Updating sysctl.conf..."
  sed -i.bak -e "/^fs.file-max = 2048000/a vm.swappiness = 5" sysctl.conf
  #echo " Done."
  sysctl -p|grep '^vm.swappiness'
}

