#!/bin/ksh

YEAR=$(date "+%Y")
STAGING=/var/tmp/staging
SPLUNK=/opt/splunk
ARCHIVE=/ELI/archive
node_=$(hostname)
#Using .zip file with hostname + fqdn
hostname_fqdn=$(host $(uname -n)|awk '{print $1}')
env_=`uname -n|grep -o '...$'`

case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               gid=unx_60231_splunk_admin_dev
               ;;
   some_loc | loc2 ) uid=ser_act.prod
               gid=unx_9998_access
               ;;
esac

usage() {

cat<<++
Invalid Option!!!
USAGE:  $0 RELEASE_ID | CRQ#

  where
        RELEASE_ID = i.e. -> 20140114A
        CRQ# Change Request Number

++

}

[[ -z $1 ]] && {
  usage
  exit 1
}

cd ${SPLUNK} && {
      echo "Backup Splunk config files to /opt/splunk/${node_}-etc-${1}.zip"
      echo "zip -qr ${node_}-etc-${1}.zip etc/*"
      zip -qr ${node_}-etc-${1}.zip etc/*
      chown ${uid}:${gid} ${node_}-etc-${1}.zip
      ls -l ${node_}-etc-${1}.zip
      echo "Done."
}
