#!/bin/bash

mount|grep hadoop >/dev/null
if [[ "$?" != "0" ]]
then
   mount /hadoop >/dev/null 2>&1
   {
     echo "Mounting `uname -n`: /hadoop"
   } | mailx -s "`uname -n`: /hadoop is now remounted" user1@mycorp.com,user2@mycorp.com
fi
