#!/bin/ksh
# NOTE: To run this script as a daemon
# nice -n 19 echo ./check_ITRS_HECs|at now
# or
# nohup nice -n 19 ./check_ITRS_HECs &
LOCAL_BIN=/usr/local/bin
user_list="user1@mycorp.com,user2@mycorp.com"

ITRS_HECs="ser14346some_loc
cud1-008660
ser14347some_loc
ser14348some_loc
ser14349some_loc
ser14346loc2
ser14347loc2
ser14348loc2
ser14349loc2"

date_=$(date '+%a%H%M_%m%d%Y')

  
while [ 1 ]
do
 for node in ${ITRS_HECs}
 do
  echo $node
  ping -c 1 $node >/dev/null 2>&1
  [[ "$?" != "0" ]] && \
     echo "ITRS HEC ${node} is NOT pingable"|mailx -s "ITRS HEC ${node} is DOWN" ${user_list}
  ssh ${node} "${LOCAL_BIN}/check_HEC" 2>/dev/null
 done
 echo
 echo "Shall returns in 1 min."
 sleep 10m
done
