#!/bin/ksh
users="user1@mycorp.com,user2@mycorp.com"
{
 jldsh -eg ITSI_SH,splunk_ES_SH "su - ser_act.prod -c 'chk_kvstore'"
} | while read line
do
  echo $line|grep 'ready' >/dev/null 2>&1
  [[ "$?" != "0" ]] && {
      echo $line | mailx -s "CRITICAL:Issue with kvstore" ${users}
  }
done

