#!/bin/bash
SPLUNK_APPS=/opt/splunk/etc/apps
SPLUNK_USERS=/opt/splunk/etc/users
bold_yellow="\e[1m\e[33m"
green=$(tput setaf 2)
red=$(tput setaf 1)
reset_color="\e[0m"

echo
echo -en "Enter file name in ${bold_yellow}/tmp/User.DELETE${reset_color}, or ${bold_yellow}user(s) separated by a space${reset_color}? "
read _input

echo
echo -en "Enter a pattern, for example, \"${bold_yellow}.meta:owner${reset_color}\"? "
read pattern_
echo
echo ${_input}|grep '/tmp/User.DELETE' >/dev/null
if [[ "$?" = "0" ]]
then
     _input=`cat /tmp/User.DELETE`
     [[ ! -s /tmp/User.DELETE ]] && echo "/tmp/User.DELETE doesnot exist. Abort" && exit
fi

echo "Checking users: "
echo -e "${bold_yellow}${_input}${reset_color}"
echo
{
for user in ${_input}
do
  cd ${SPLUNK_USERS} && {
     if [[ -d ${user} ]]
     then
        echo -en "${bold_yellow}${user}${reset_color} :"
        cd ${SPLUNK_APPS} &&  {
           grep -ir "${user}" * | grep -c  "${pattern_}"
        }
     else
        echo -e "${bold_yellow}${user}${reset_color} : DOESNOT_exist"
     fi
  }
done
} | tee /var/tmp/check_stale_users.OUT

echo "Output: /var/tmp/check_stale_users.OUT"

