#!/bin/bash

# According to Splunk Best Practice by Splunk's Manu Jose, Yuan Xu Sr. Software Engineer
# Rolling restart from the captain maintains the node as captain after restarts
UID_="ser_act.prod"

echo -n "Enter a SH nodename? "
read search_head

# Identify all members in the cluster
echo "Below are all members in $search_head SH cluster:"
ssh ${search_head} "su - ${UID_} -c \"/opt/splunk/bin/splunk show shcluster-status -auth admin:\`uname -n\`_admin\"" 2>/dev/null|grep label|awk '{print $NF}'|sort|uniq

all_search_heads=`ssh ${search_head} "su - ${UID_} -c \"/opt/splunk/bin/splunk show shcluster-status -auth admin:\`uname -n\`_admin\"" 2>/dev/null|grep label|awk '{print $NF}'|sort|uniq`
echo all_search_heads=${all_search_heads}

# 
[[ -z "${all_search_heads}" ]] && {
   echo "${search_head}, is splunkd down? Operation Abort."
   exit
}

# Identify captain
captain=`ssh ${search_head} "su - ${UID_} -c \"/opt/splunk/bin/splunk list shcluster-members -auth admin:\`uname -n\`_admin\"" 2>/dev/null|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}'`
echo captain=$captain
# Check captain splunk version
splunk_version=`ssh $captain "/opt/splunk/bin/splunk -version|awk '{print $2}'" 2>/dev/null`
echo "Captain Splunk version: $splunk_version"


