#!/bin/ksh
SPLUNK_BIN=/opt/splunk/bin
{
eval `gpg --batch --xyz xyz -quiet --no-verbose -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
su - ser_act.prod -c "${SPLUNK_BIN}/splunk login -auth admin:$prod;${SPLUNK_BIN}/splunk show kvstore-status|grep status|sed 's/[[:space:]]//g'"
