#!/bin/bash
#
########################################################################################
# This script will be run twice/week, ie, Tuesday and Thursday@10:00 PM EST
# Removed files/folder will be stored in ${DISPATCH_LOG_CLEANUP}
########################################################################################
DISPATCH=/opt/splunk/var/run/splunk/dispatch
SPLUNKDIR=/opt/splunk
DISPATCH_LOG_CLEANUP=${SPLUNKDIR}/DISPATCH_LOG_CLEANUP
date_=$(date '+%F')
#
# clean out anything older than MTIME days:
MTIME=7
#
{
[[ ! -d ${DISPATCH_LOG_CLEANUP} ]] && mkdir -p ${DISPATCH_LOG_CLEANUP}
echo "###############################################################"
echo "1. Clean up $DISPATCH with splunk search artifacts > 7 days old"
echo "###############################################################"
find ${DISPATCH} -maxdepth 1 -mtime +${MTIME} 2>/dev/null | \
while read job
do
 if [ ! -e "$job/save" ]
 then
   ls -ld $job
   rm -rf $job
 fi
done

echo
echo "###############################################################"
echo "2. Clean up $DISPATCH empty folder: alive.token"
echo "###############################################################"
find ${DISPATCH} -type d -empty -name alive.token -mtime +${MTIME} -exec ls -ld {} +
find ${DISPATCH} -type d -empty -name alive.token -mtime +${MTIME} 2>/dev/null | xargs -i rm -Rf {}

echo
echo "###############################################################"
echo "3. Clean up ${SPLUNKDIR}/var/run/splunk/ session-*"
echo "###############################################################"
find ${SPLUNKDIR}/var/run/splunk/ -type f -name "session-*" -mtime +${MTIME} -exec ls -ld {} +
find ${SPLUNKDIR}/var/run/splunk/ -type f -name "session-*" -mtime +${MTIME} 2>/dev/null | xargs -i rm -Rf {}
} | tee ${DISPATCH_LOG_CLEANUP}/`basename $0`.${date_}

exit 0

