#!/bin/bash
# Run as root from ser10966some_loc
echo "1. Put CD1_D Cluster master, ser24-010472, in Maitenance mode"
jldsh -ew ser24-010472 "su - ser_act.prod -c 'echo y|start_maintenance'"
echo " Verifying ..."
jldsh -ew ser24-010472 "su - ser_act.prod -c 'show_maintenance'"
echo "2. Put all CD1_D indexers in Detention mode"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "set_idx_detention on"
echo "Verifying ..."
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "check_detention_status"
echo "3. Verifying traffic on Indexers port 9990. Count should be 0."
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "netstat -an|grep ':9990'|wc -l"
echo "4. Stopping Splunkd on All LUMP:CD1_D_All_DC74_E-F_core_site12"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "systemctl stop Splunkd"
sleep 10s
echo "Verifying splunkd stopped. Count should be 0."
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "pgrep splunkd|wc -l"
echo "5. Unmounting /opt/splunkindex_data"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "umount /opt/splunkindex_data"
echo "6. Cleaning up /opt/splunkindex_data"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "mkfs.ext4 -m 1 /dev/splunkvg/splunkindex_lv"
echo "7. Mounting /opt/splunkindex_data and change uid:gid /opt/splunkindex_data"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "mount -a && chown -R ser_act.prod:unx_9998_access /opt/splunkindex_data"
echo "8. Startting splunkd"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "systemctl start Splunkd"
echo "Verifying Splunkd"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "pgrep splunkd|wc -l"
echo "9. Taking CD1_D_All_DC74_E-F_core_site12 Indexers out of Detention mode"
jldsh -eg CD1_D_All_DC74_E-F_core_site12 "set_idx_detention off"
echo "10. Taking CD1_D Cluster master, ser24-010472, out of Maitenance mode"
jldsh -ew ser24-010472 "su - ser_act.prod -c 'stop_maintenance'"
echo "Verifying..."
jldsh -ew ser24-010472 "su - ser_act.prod -c 'show_maintenance'"







