#!/bin/bash

echo "1. Cleaning /opt/splunk/etc/peer-apps.old.bkp"
[[ -d /opt/splunk/etc/peer-apps.old.bkp ]] && rm -rf /opt/splunk/etc/peer-apps.old.bkp
echo "2. Cleaning up old ES and ITSI Search artifacts"
#echo -n "Total: "
cd /opt/splunk/var/run/searchpeers && {
  find . -type d \( -name 's0302some_loc*' -o -name 's3110loc2*' -o -name 's0303some_loc*' -o -name 's0163loc3*' -o -name 's0182loc3*' -o -name 's3110some_loc*' -o -name 's3111some_loc*' -o -name 's3111loc2*' -o -name 's0978loc2*' -o -name 's0160loc3*' -o -name 's0161loc3*' -o -name 's0162loc3*' -o -name 's0180loc3*' -o -name 's0181loc3*' \) -exec rm -rf {} +
  find . -type f \( -name 's0302some_loc*' -o -name 's3110loc2*' -o -name 's0303some_loc*' -o -name 's0163loc3*' -o -name 's0182loc3*' -o -name 's3110some_loc*' -o -name 's3111some_loc*' -o -name 's3111loc2*' -o -name 's0978loc2*' -o -name 's0160loc3*' -o -name 's0161loc3*' -o -name 's0162loc3*' -o -name 's0180loc3*' -o -name 's0181loc3*' \) -exec rm -f {} +
}
echo "3. Cleaning all files/dirs in /opt/splunk/var/run/splunk/dispatch "
cd /opt/splunk/var/run/splunk/dispatch && {
   #find . -exec rm -rf {} +
   #echo -n "Total dir to clean up: "
   find . -type d -exec rm -rf {} + 2>/dev/null
}
echo "4. /opt/splunk, cleaning old diags and etc-splunk-8.1.5.tar.gz etc-splunk-9.0.4.1.tar.gz"

cd /opt/splunk && {
   rm -f diag* etc-splunk-8.1.5.tar.gz etc-splunk-9.0.4.1.tar.gz 2>/dev/null
   #ls -l diag* etc-splunk-8.1.5.tar.gz etc-splunk-9.0.4.1.tar.gz 2>/dev/null
}

