#!/bin/bash
SPLUNK_SNAPSHOT=/opt/splunk/var/run/splunk/snapshot

cd ${SPLUNK_SNAPSHOT} && {
   # Get total .bundle count 
   bundle_count=$(ls -Art *.bundle|wc -l)
   if [[ ${bundle_count} -gt 1 ]]
   then
     echo "Below are list of current .bundle:"
     ls -ltr
     # Identify latest bundle
     latest=`ls -Art  | tail -n 1`
     echo "Latest bundle:"
     ls -ltr ${latest}
     echo "Below are list of .bundle to remove:"
     find . -type f ! -name  ${latest} ! -newer ${latest} -exec ls -ltr {} +
     find . -type f ! -name  ${latest} ! -newer ${latest} -exec rm -f {} +
   else
     echo "There's only 1 .bundle. Proceed with backing up ${SPLUNK_SNAPSHOT}"
   fi 
}
   
