#!/bin/ksh
jldsh -ew s0338some_loc  "cd /root/HDD && cp \`uname -n\`.cold /tmp;chown ser_act.prod /tmp/\`uname -n\`.cold;su - ser_act.prod -c \"mv -f /tmp/\`uname -n\`.cold /ELI/daily_strace/HDD\""
jldsh -ew s0338some_loc  "cd /root/SSD && cp \`uname -n\`.hot /tmp;chown ser_act.prod /tmp/\`uname -n\`.hot;su - ser_act.prod -c \"mv -f /tmp/\`uname -n\`.hot /ELI/daily_strace/SSD\""
