#!/bin/bash
{
SPLUNK_HOME=/opt/splunk

echo -n "Enter remote hostname (ser11989some_loc)? "
read node
echo -n "Enter Destination where app will be copied to, ie, (/opt/splunk/etc/shcluster/apps) "
read dest

# Create $dest if doesn't exist.

jldsh -ew $node "[[ ! -d $dest ]] && mkdir -p $dest"
echo
echo "Remote hostname: $node"
echo "Destination: $node:$dest"
echo

cat sh_app.list | \
while read sh_ app
do
  app_=`echo $app|awk -F"/" '{print $NF}'`
  echo "Copying ${sh_}:${SPLUNK_HOME}/etc/apps/${app_} to ${node}:$dest/${app_}"
  # Get etc/apps/${app} and etc/users/*/${app}
  #ssh -n -o StrictHostKeychecking=no ${sh_} "cd ${SPLUNK_HOME}/etc/apps;find ${app_} |cpio -oBc" 2>/dev/null|ssh ${node} "cd $dest;cpio -iBcdmvu" 2>/dev/null
  #ssh -n ${sh_} "cd ${SPLUNK_HOME}/etc/apps;find ${app_} |cpio -oBc" 2>/dev/null|ssh ${node} "cd $dest;cpio -iBcdmvu" 2>/dev/null
  ssh -n ${sh_} "cd ${SPLUNK_HOME}/etc;find  apps/${app_} users/*/${app_} -print|cpio -oBc" 2>/dev/null|ssh ${node} "cd $dest;cpio -iBcdmvu" 2>/dev/null
  # Get /etc/users/*/${app}
done
} | tee `basename $0.OUT`

