#!/bin/bash
check_DISK ()
{
 flag=false
 while [[ "$flag" = "false" ]]
 do
   if [[ ! -b $1 ]]
   then
     echo "Pause for 3 seconds."
     sleep 3s
   else
    flag=true
   fi
 done
}
          echo "Creating /opt/splunkindex_data filesystem"
          # Is it?
          # Disk /dev/sdb: 447.1 GiB, 480036847616 bytes, 937571968 sectors
          # Disk /dev/sda: 24.5 TiB, 26876026290176 bytes, 52492238848 sectors
          root_disk=$(fdisk -l|grep '/dev/sd'|grep '^Disk'|awk '/447.1 GiB/{print $2}'|sed 's/://g')
          if [[ "${root_disk}" = "/dev/sdb" ]]
          then
             DISK=/dev/sda
          else
             DISK=/dev/sdb
          fi
          check_DISK $DISK
          if [[ -b ${DISK} ]]
          then
            echo "Formatting ${DISK}:"
            parted -s ${DISK} mklabel gpt
            parted -s ${DISK} unit TB mkpart primary ext4 0% 100%
            partprobe
            echo "Creating physical volume ${DISK}1"
            pvcreate -f ${DISK}1
            echo "Creating splunk volume group: splunkvg"
            vgcreate splunkvg ${DISK}1
            echo
            echo "Creating splunk Index logical volume: splunkindex_lv"
            lvcreate -y -l 100%FREE -n splunkindex_lv splunkvg
            echo
            echo "Creating /dev/splunkvg/splunkindex_lv filesystem"
            mkfs.ext4 -m 1 /dev/splunkvg/splunkindex_lv
          else
            echo "${DISK} doesnot exist. Abort."
            exit
          fi

