#!/bin/bash
#pass4SymmKey = $7$is6eTEQfMkbA6ES7tQvMVYqakA5WvVHLG3FUuWGUwxJDKbwM2dT+wA==
pass4SymmKey='$7$dE62DFIjwOgFuT/MsP9k8WJwh+NSIG8/0u1FYiYWpL11IGlu90R3/7Fe5BLsLEz6mBc='
env_=`uname -n|grep -o '...$'`
echo "pass4SymmKey=$pass4SymmKey"

case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               gid=unx_60231_splunk_admin_dev
               ;;
   some_loc | loc2 | loc3 ) uid=ser_act.prod
               gid=unx_9998_access
               ;;
           * )
               case `uname -n` in
                   ser2* ) uid=ser_act.prod
                           gid=unx_9998_access
                           ;;
                   cud*| cut* ) uid=ser_act.dev
                                  gid=unx_60231_splunk_admin_dev
                           ;;
               esac
               ;;
esac

uid=ser_act.prod
su - ${uid} -c "/opt/splunk/bin/splunk show-decrypted --value \'${pass4SymmKey}\'"
