#!/bin/ksh
exception_list="secops_summary|restricted_secops|restricted_secops_summary|bluecoat|bluecoat_summary|ids|ids_summary|ti_summary|network_summarydb|network_summary2db|network_summary3db|traffic_center_summarydb|traffic_center_summary2db|proxy_center_summarydb|proxy_center_summary2db|whoisdb|access_summarydb|access_summary2db|audit_summarydb|audit_summary2db|cim_summarydb|cim_summarydb|endpoint_summarydb|endpoint_summary2db|notabledb|notable_summarydb|session_startdb|session_enddb|secops_snare_win_dc|secops_snare_win_ua|secops_snare_win_oa|secops_sys_nix_auth|secops_sys_nix_apps|secops_sys_nix_oth|secops_sys_nix_stg|secops_sys_nw_fw|secops_sys_nw_oth|secops_sys_cef_as|secops_sys_cef_ids|secops_sys_cef_oth|secops_ftp_bc_groupa|secops_ftp_bc_groupb|secops_ftp_bc_groupc|secops_ftp_bc_groupd|iocdb|threat_activitydb|riskdb|cim_modactionsdb|xtreme_contexts|gia_summary|secops_data_classification|secops_mcafee_epo"

cd /opt/splunkindex_data && {
 find . -type d -name "hot*" -print|awk -F/ '{print $2}'|egrep -v "${exception_list}"|sort|uniq|tee /var/tmp/copy.list
}
