#!/bin/ksh

F5_fqdn='splunk.mycorp.com'
F5_fqdn='splunk-preprod.mycorp.com'
F5_fqdn='splunk-restapi.mycorp.com'
#F5_fqdn='splunktest.dev.mycorp.com'
F5_fqdn='splunk-qa.dev.mycorp.com'
#F5_fqdn='splunk-extracts.mycorp.com'
#F5_fqdn='splunk-es.mycorp.com'
#F5_fqdn='splunk-itsi.mycorp.com'
#F5_fqdn='splunktest.dev.mycorp.com'
#F5_fqdn='splunk-dev.dev.mycorp.com'
#Note: 5/28/2021 still waiting for MyIT F5 F5_fqdn='splunk-preprod.mycorp.com' to complete

#{
#eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
#} 2>/dev/null

#echo ${F5_fqdn}|grep 'dev' >/dev/null
#if [[ "$?" = "0" ]]
#then
#  key=${dev}
#else
#  key=${prod}
#fi

get_hostname ()
{
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
echo ${F5_fqdn}|grep 'dev' >/dev/null
if [[ "$?" = "0" ]]
then
  key=${dev}
else
  key=${prod}
fi
echo key=$key
curl -k -u admin:${key} https://${F5_fqdn}:8089/services/server/info|grep "host_fqdn">/tmp/$$ 2>&1
}

#for F5_fqdn in splunk.mycorp.com splunktest.dev.mycorp.com splunk-qa.dev.mycorp.com splunk-extracts.mycorp.com splunk-es.mycorp.com splunk-itsi.mycorp.com splunk-dev.dev.mycorp.com splunk-preprod.mycorp.com splunk-itsi-qa.dev.mycorp.com splunk-es-qa.dev.mycorp.com splunk-lab.dev.mycorp.com
#for F5_fqdn in splunk-dev.dev.mycorp.com
#for F5_fqdn in splunk-restapi.mycorp.com splunk-restapi-qa.dev.mycorp.com splunk-restapi-dev.dev.mycorp.com
for F5_fqdn in splunk.mycorp.com
do
 echo -n "${F5_fqdn}: "
jas=`
{
get_hostname 2>/dev/null
cat /tmp/$$|awk -F'>' '{print $2}'|sed 's/<\/s:key//g'
#[[ "${F5_fqdn}" = "splunk-preprod.mycorp.com" ]] && cat /tmp/$$
rm -f /tmp/$$ 
}`
echo $jas
done
