#!/bin/ksh
###########################################################################
# https://jira.mycorp.com/browse/PAMEE-181
# Processes/Steps to get to the point to run this script
# 1. Submitted MyIT#19104338/WO0000007913029 to create 
#    Group Name: app_venafi_sg_AD00101503/APM Application ID: AD00101503
# 2. Via https://myit.mycorp.com/dwp/app/#/itemprofile/4102, 
#    submitted MyIT#1783769 to create in 
#    https://venafi.mycorp.com/aperture/
#    Once  MyIT#1783769 completed,
#    \VED\Policy\mycorp\SafeGuard\Certificates\AD00101503 will be visible.
# 3. Under \VED\Policy\mycorp\SafeGuard\Certificates\AD00101503
#    Follow https://confluence.mycorp.com/display/SESD/Safeguard+API+Certificate+Creation
#    to create
#    \VED\Policy\mycorp\SafeGuard\Certificates\AD00101503\splunk.prod.safeguard
# 4. Follow https://confluence.mycorp.com/display/SESD/Safeguard+API+Registration
#    created Privileged Access Vault MyIT#1820230
#    Common Name: splunk.prod.safeguard
#    Certificate Distinguished Name: 
#    \VED\Policy\mycorp\Safeguard\Certificates\AD00101503\splunk.prod.safeguard
# 5. Obtained CA_Bundle_Prod.cer from Brandon Benson and copy this cert to
#    ser10966some_loc's $CLUSTER's LUMP:All_Weblogs_splunk_extract_server
#    ~/ser_act.prod/Safeguard_Cert
# 6. In Venafi ${Certificate Distinguished Name} in 4., created devices
#    Note: Leave Subject Alt Name(s): blank
# 7. On ser10966some_loc, push Venafi public key to all devices:
#    jldsh -eg All_Weblogs_splunk_extract_server -s ./push_Venafi_public_key
# 8. Login to https://venafi.mycorp.com/aperture/, click on 
#    splunk.prod.safeguard's Settings Tab then click on "Renew Now" tab
#    then verify /ser_act.prod/Safeguard_Cert/safeguard.[cer|key]
###########################################################################
# Written by user1 | Splunk Platform Support
#
safeguard_url=https://safeguard-api.mycorp.com/service
CA_Bundle_Prod_cer=/ser_act.prod/Safeguard_Cert/CA_Bundle_Prod.cer
safeguard_cer=/ser_act.prod/Safeguard_Cert/safeguard.cer
safeguard_key=/ser_act.prod/Safeguard_Cert/safeguard.key


get_Id ()
{
  {
    curl --cacert ${CA_Bundle_Prod_cer} \
         -X GET "${safeguard_url}/core/v3/A2ARegistrations" \
         -H "accept: application/json" \
         -H "Content-Type: application/json" \
         --cert ${safeguard_cer} \
         --key ${safeguard_key}
  } 2>/dev/null | jq |grep '"Id":'|awk '{print $NF}'|sed 's/,//g'
}

get_ApiKey ()
{
  {
    curl --cacert ${CA_Bundle_Prod_cer} \
         -X GET "${safeguard_url}/core/v3/A2ARegistrations/${Id}/RetrievableAccounts" \
         -H "accept: application/json" \
         -H "Content-Type: application/json" \
         --cert ${safeguard_cer} \
         --key ${safeguard_key}
  } 2>/dev/null |jq|grep -A1 "ser_act.prod" \
                |awk '/"ApiKey":/{print $NF}'\
                |sed -e 's/"//g' -e 's/,//g'
}

get_safeguard_pass ()
{
  {
    curl --cacert ${CA_Bundle_Prod_cer} \
         -H "Authorization: A2A $ApiKey" \
         -H "accept: application/json" \
         -H "Content-Type: application/json" \
            "${safeguard_url}/a2a/v3/Credentials?type=Password" \
         --cert ${safeguard_cer} \
         --key ${safeguard_key}
  } 2>/dev/null|jq|sed 's/"//g'
}

Id=$(get_Id)
ApiKey=$(get_ApiKey)
safeguard=$(get_safeguard_pass)
echo $safeguard
