#!/bin/ksh

get_hostname ()
{
#  {
#    eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
#  } 2>/dev/null

  # DEV/QA or PROD?
  . /.jas
  echo ${F5_fqdn}|grep 'dev' >/dev/null
  if [[ "$?" = "0" ]]
  then
    key=${dev}
  else
    key=${prod}
  fi

 {
  curl -k -u admin:${key} https://${F5_fqdn}:8089/services/server/info 2>/dev/null
 } |grep "host_fqdn" | awk -F'>' '{print $2}'|sed 's/<\/s:key//g'
}

cat<<END
Splunk F5 LB:

splunk.mycorp.com
splunk-preprod.mycorp.com
splunktest.dev.mycorp.com
splunk-qa.dev.mycorp.com
splunk-extracts.mycorp.com
splunk-es.mycorp.com
splunk-itsi.mycorp.com
splunktest.dev.mycorp.com
splunk-dev.dev.mycorp.com

END

echo -n "Enter SH F5 LB info? "
read F5_fqdn
echo -n "${F5_fqdn}: "
get_hostname 2>/dev/null

echo -n "$F5_fqdn captain:"
curl -k -u admin:${key} https://${F5_fqdn}:8089/services/shcluster/captain/info 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g'

captain=`curl -k -u admin:${key} https://${F5_fqdn}:8089/services/shcluster/captain/info 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g'`
echo "And its search peers: "
curl -k -u admin:${key} https://${captain}:8089/services/shcluster/captain/members 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g'
