#!/bin/bash
env_=`uname -n|grep -o '...$'`
adddate(){
    while IFS= read -r line; do
        printf '%s %s %s\n' "`date`" "`uname -n`" "$line";
    done
}

get_key ()
{
  {
    eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
  } 2>/dev/null
  case ${env_} in
         pdv | bdv ) uid=ser_act.dev
                     key=${dev}
                     ;;
   some_loc | loc2 | loc3 ) uid=ser_act.prod
                     key=${prod}
                     ;;
                 * )
                     case `uname -n` in
                               ser2* ) uid=ser_act.prod
                                      key=${prod}
                                      ;;
                         cud*| cut* ) uid=ser_act.dev
                                      key=$dev
                                      ;;
                    esac
                    ;;
  esac
  S2H_CONF="/${uid}/S2H_CONF"
  # Generate MapR Ticket
  if [[ -f /.s2h_mapr.key ]]
  then
    uid_key=`ssh -o StrictHostKeyChecking=no -o BatchMode=yes \
             -i /.s2h_mapr.key SPLUNK_S2H_CLI@passwords.mycorp.com \
             retrieve --systemname USDomain --accountname ${uid}`
    echo ${uid_key}| maprlogin password -out /tmp/$$ >/dev/null
    MAPR_TICKETFILE_LOCATION=/tmp/$$
    # Verify mapr ticket credential
    if [[ -f $MAPR_TICKETFILE_LOCATION ]]
    then
       export MAPR_TICKETFILE_LOCATION=${MAPR_TICKETFILE_LOCATION}
    else
       echo "ERROR: ${MAPR_TICKETFILE_LOCATION} does not exist. Abort" |adddate
       exit
    fi
  else
    echo "ERROR: /.s2h_mapr.key does not exist. Abort." |adddate
    exit
  fi
}

get_key
echo "uid=$uid"
#echo "key=$key"
#echo "uid_key=${uid_key}"
echo "MAPR_TICKETFILE_LOCATION=${MAPR_TICKETFILE_LOCATION}"
echo
echo "##########################################"
cat ${MAPR_TICKETFILE_LOCATION}
echo "##########################################"
echo "TESTING"
hadoop fs -ls -R maprfs:///bdh/raw/eli/CXP/cwp_new/JASTEST|head -3
echo "Clean up /tmp/$$"
[[ -f /tmp/$$ ]] && rm -f /tmp/$$
