#!/bin/ksh

F5_fqdn='splunk.mycorp.com'
F5_fqdn='splunk-preprod.mycorp.com'
#F5_fqdn='splunktest.dev.mycorp.com'
F5_fqdn='splunk-qa.dev.mycorp.com'
#F5_fqdn='splunk-extracts.mycorp.com'
#F5_fqdn='splunk-es.mycorp.com'
#F5_fqdn='splunk-itsi.mycorp.com'
#F5_fqdn='splunktest.dev.mycorp.com'
#F5_fqdn='splunk-dev.dev.mycorp.com'
#Note: 5/28/2021 still waiting for MyIT F5 F5_fqdn='splunk-preprod.mycorp.com' to complete

get_hostname ()
{
#  {
#    eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
#  } 2>/dev/null

  # DEV/QA or PROD?
  . /.key
  echo ${F5_fqdn}|grep 'dev' >/dev/null
  if [[ "$?" = "0" ]]
  then
    key=${dev}
  else
    key=${prod}
  fi

 {
  curl -k -u admin:${key} https://${F5_fqdn}:8089/services/server/info 2>/dev/null
 } |grep "host_fqdn" | awk -F'>' '{print $2}'|sed 's/<\/s:key//g'
}

#for F5_fqdn in splunk.mycorp.com splunktest.dev.mycorp.com splunk-qa.dev.mycorp.com splunk-extracts.mycorp.com splunk-es.mycorp.com splunk-itsi.mycorp.com splunk-dev.dev.mycorp.com splunk-preprod.mycorp.com splunk-itsi-qa.dev.mycorp.com splunk-es-qa.dev.mycorp.com splunk-lab.dev.mycorp.com
#for F5_fqdn in splunk-dev.dev.mycorp.com
#for F5_fqdn in splunk.mycorp.com
#for F5_fqdn in splunk-restapi-dev.dev.mycorp.com splunk-restapi-qa.dev.mycorp.com splunk-restapi.mycorp.com
for F5_fqdn in splunk-restapi-qa.dev.mycorp.com
do
 echo -n "${F5_fqdn}: "
 get_hostname 2>/dev/null
done

exit
#echo -n "splunk.mycorp.com captain:"
curl -k -u admin:${key} https://${F5_fqdn}:8089/services/shcluster/captain/info 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g'

captain=`curl -k -u admin:${key} https://${F5_fqdn}:8089/services/shcluster/captain/info 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g'`
echo "And its search peers: "
sh_peers=$(curl -k -u admin:${key} https://${captain}:8089/services/shcluster/captain/members 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g')
echo sh_peers=$sh_peers
