#!/bin/bash
##################################################################################
# This script performs the followings,
# 1. Determine when Splunk.service last started, then convert the time in epoch
#    seconds
# 2. Determine, in splunkd.log, 'Client initialized successfully' entry's time 
#    stamp then convert to epoch seconds
#
# Different in minutes/seconds will be gauged among all members in DS Farm
# to determine if DS Farm restart is complete.
#
# References:
# - https://jira.mycorp.com/browse/TOS-20023
# - Splunk Multi-Deployment Server Architecture
#   https://conf.splunk.com/files/2019/slides/FN2048.pdf
# - Multiple Deployment Server, VIP Load Balancer
#   https://community.splunk.com/t5/Deployment-Architecture/Multiple-Deployment-Server-VIP-Load-Balancer-and-NO-CLIENTS/m-p/519924
# - On each Deployment Server's /usr/local/bin, get_splunkd_DS_start_time
#   will show, for example
#   ser24-011648: Splunkd start up process completed in 109 secs, or 1 min(s) and 49 secs
#
# NOTES:
# . Dependencies:
#    - ser10934some_loc:/usr/local/bin/stage_FwdrApps_to_Deployment_Server_Farm
#    - ser10966some_loc:/usr/local/bin/restart_splunk_DS 
#    - ser10966some_loc's $CLUSTER's GROUP:All_splunk_DS_Farm
##################################################################################
# Written by user1 | T.O.S Platform S.P.L.U.N.K
# With user2 Llamado's collaboration.
#
SPLUNK_LOG=/opt/splunk/var/log/splunk
date

echo "- Splunkd.service Start time:"
systemctl status Splunkd|grep Active|sed 's/^[ \t]*//g'
start_time=`systemctl status Splunkd|grep Active|awk '{printf("%s %s\n",$6,$7)}'`
start_time_e=$(date --date="$start_time" +%s)
echo "Splunkd.service start time in seconds --> $start_time_e"
echo

# Check splunkd.log
# splunkd.log.2:10-18-2023 16:43:53.147 -0400 INFO  DS_DC_Common [237934 MainThread] - Deployment |Client initialized successfully.
grep 'Client initialized successfully' ${SPLUNK_LOG}/splunkd.log >/dev/null
if [[ "$?" = "0" ]]
then
    splunkd_log=splunkd.log
else
    splunkd_log=splunkd.log.1
fi
echo "- Verifying splunkd.log's Client initialized successfully:"
line=`grep 'Client initialized successfully' ${SPLUNK_LOG}/${splunkd_log} | tail -1`
echo $line
echo
date_=`echo $line|awk '{print $1}'`
time_=`echo $line|awk '{print $2}'`

# Reformat 10-18-2023 16:43:53.147 --> 2023-10-18 16:43:53
date_e=`echo ${date_}|awk -F- '{printf("%s-%s-%s\n",$3,$1,$2)}'`
time_e=`echo ${time_}|awk -F. '{print $1}'`
#echo date_e=$date_e
#echo time_e=$time_e
# Convert to secs
splunkd_t=$(date --date="$date_e $time_e" +%s)
echo "splunkd.log's \"Client initialized successfully\" in seconds --> $splunkd_t"
echo
# Calculate time (in seconds) from when Splunkd start until splunkd.log's
# Client initialized successfully

time_in_secs=`expr $splunkd_t - $start_time_e`
echo -n "Splunkd start up process completed in $time_in_secs secs, or "
echo "$((${time_in_secs}/60)) min(s) and $((${time_in_secs}%60)) secs"


