#!/bin/ksh

get_key ()
{
  env_=`echo $1 | awk -F. '{print $1}'|grep -o '...$'`
  echo env_=$env_
  {
    eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
  } 2>/dev/null
  case ${env_} in
         pdv | bdv ) uid=ser_act.dev
                     key=${dev}
                     ;;
   some_loc | loc2 | loc3 ) uid=ser_act.prod
                     maprticket=maprticket_500327
                     key=${prod}
                     ;;
                 * )
                     case $1 in
                               ser2* ) uid=ser_act.prod
                                      key=${prod}
                                      ;;
                         cud*| cut* ) uid=ser_act.dev
                                      key=$dev
                                      ;;
                    esac
                    ;;
  esac
}

echo -n "Enter hostname? "
read host_
get_key $host_
echo key=$key

