#!/bin/bash

if [[ $# = 0 ]]
then
   echo "Enter node(s) name separate by a space, or "
   echo -n "Filename and its location which contains nodes? "
   read file_
   echo ${file_}|grep '/' >/dev/null
   if [[ "$?" = "0" ]]
   then
      if [[ -f ${file_} ]]
      then
         nodes=`cat ${file_}`
      else
         echo "${file_} doesnot exist."
         exit
      fi
    else
      nodes=${file_}
    fi
else
   nodes=$@
fi

echo nodes=$nodes
echo

for server in $nodes
do
  ip=`host $server|awk '{print $NF}'`
  echo -n "${server}: ${ip} "
  network_router=$(traceroute $server|grep -iB1 $server|egrep 'rpan|float|loc3|vlan'|grep -v $server|awk '{print $2}')

  if [[ ! -z ${network_router} ]]
  then
    network_core=$(echo ${network_router}|awk -F- '{print $1}')
    # Extract the lsat 2 chars
    network_core=${network_core:(-2)}
    network_core=$(echo $network_core|tr [a-z] [A-Z])
    echo "${network_router} ${network_core}"
  else
    traceroute $server|grep -B1 $server|grep -v $server|tail -1
  fi
done
