#!/bin/ksh
[[ `uname -n` = "ser15000some_loc" ]] && {
   echo "Running $0 on wrong node: ser15000some_loc"
   exit
}

{
# Written by JPD.
# If splunk splunk-6.6.3-e21ee54bc796.x86_64 installed then exit
[[ "`rpm -q splunk`" = "splunk-6.6.3-e21ee54bc796.x86_64" ]] && {
  echo "splunk-6.6.3-e21ee54bc796.x86_64 installed. Abort."
  exit
}
# Check if perccli installed.
rpm -q perccli >/dev/null
[[ "$?" != "0" ]] && {
   host `hostname`|grep 'ser1' >/dev/null
   [[ "$?" != "0" ]] && {
      umount -l /mnt
      mount share_server.dev.mycorp.com:/infra/loc /mnt
      cd /mnt/Splunk && rpm -ivh perccli-1.11.03-1.noarch.rpm
      ln -s /opt/MegaRAID/perccli/perccli64 /usr/local/bin/perccli
   }
}
   

# I. Configure /opt/splunkindex_data and /opt/splunkindexhot_data
DISK=`fdisk -l|grep '/dev/sd'|grep -v '/dev/sda'|awk '/dev/{print $2}'|sed 's/://g'`
fdisk -l|grep "Disk ${DISK}: 805.3 GB" >/dev/null
if [ "$?" = "0" ]
then
   echo -e "o\nw\n" | fdisk ${DISK}
   echo -e "n\np\n1\n\n\nw\n" | fdisk ${DISK}
   partprobe
   pvcreate ${DISK}1
   vgcreate splunkvg ${DISK}1
   # Create hot and cold lvm
   lvcreate -L 500G -v splunkvg -n coldlv
   lvcreate -l 100%FREE -n hotlv splunkvg
   # Create ext4
   mkfs.ext4 -m 1 /dev/splunkvg/coldlv
   mkfs.ext4 -m 1 /dev/splunkvg/hotlv
else
   echo "Disk ${DISK} doesnot exit. Abort!"
   exit
fi


# Update mount table with /opt/splunkindex_data, /opt/splunkindexhot_data and NAS /ELI
grep 'splunkindexhot_data' /etc/fstab >/dev/null
if [ "$?" != "0" ]
then
   {
    cat /etc/fstab
    echo '/dev/splunkvg/coldlv /opt/splunkindex_data ext4 noatime,errors=remount-ro 1 1'
    echo '/dev/splunkvg/hotlv /opt/splunkindexhot_data ext4 noatime,discard,data=ordered,errors=remount-ro  1 2'
    echo 'nas30u0pdv.dev.mycorp.com:/eli_splunk/eli_splunk_nonprod  /ELI  nfs  rw,bg,soft,nfsvers=3,intr  0 0'
   } > /tmp/fstab.$$

   mv /etc/fstab /etc/fstab.ORIG
   mv /tmp/fstab.$$ /etc/fstab
else
   echo "/opt/splunkindexhot_data ALREADY DEFINED in /etc/fstab"
   grep 'splunkindex' /etc/fstab
fi

# Create mount point /opt/splunkindex_data, /opt/splunkindex_data/SSD /ELI
mkdir -p /opt/splunkindex_data /opt/splunkindexhot_data /ELI
mount /opt/splunkindex_data
mount /opt/splunkindexhot_data

# Install splunk 6.6.3
umount -l /mnt
mount share_server.dev.mycorp.com:/infra/loc /mnt
cd /mnt/Splunk && rpm -ivh splunk-6.6.3-e21ee54bc796-linux-2.6-x86_64.rpm

/opt/splunk/bin/splunk enable boot-start --answer-yes --no-prompt --accept-license
service splunk start

/opt/splunk/bin/splunk login -auth admin:changeme
/opt/splunk/bin/splunk edit user admin -password `uname -n`_admin

} | tee /var/tmp/Implement_new_Indexer_VM.output
