#!/bin/bash
# Below are syslog-ng and its dependencies
# They can be obtained from 
# http://mirror.utexas.edu/epel/7/x86_64/Packages/[p|g|i|e|l|s]/
# Or

# https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/
# http://mirror.sfo12.us.leaseweb.net/epel/7/x86_64/
# http://mirror.nodesdirect.com/epel/7/x86_64/
# http://mirror.math.princeton.edu/pub/epel/7/x86_64/
# http://mirrors.syringanetworks.net/fedora-epel/7/x86_64/
# http://mirrors.rit.edu/fedora/epel/7/x86_64/
# https://mirrors.kernel.org/fedora-epel/7/x86_64/
# http://mirror.us.leaseweb.net/epel/7/x86_64/
# http://mirror.metrocast.net/fedora/epel/7/x86_64/
# http://mirror.compevo.com/epel/7/x86_64/
# http://mirror.cs.pitt.edu/epel/7/x86_64/
# http://mirror.oss.ou.edu/epel/7/x86_64/
# http://mirror.datto.com/fedora/epel/7/x86_64/
# https://mirrors.xmission.com/fedora-epel/7/x86_64/
# https://mirror.steadfast.net/epel/7/x86_64/
# http://mirror.cs.princeton.edu/pub/mirrors/fedora-epel/7/x86_64/
# http://ftp.osuosl.org/pub/fedora-epel/7/x86_64/
# http://ftp.linux.ncsu.edu/pub/epel/7/x86_64/
# https://mirrors.lug.mtu.edu/epel/7/x86_64/
# http://mirrors.mit.edu/epel/7/x86_64/
# http://linux.mirrors.es.net/fedora-epel/7/x86_64/
# http://archive.linux.duke.edu/pub/epel/7/x86_64/
# http://fedora-epel.mirrors.tds.net/fedora-epel/7/x86_64/
# http://fedora-epel.mirror.lstn.net/7/x86_64/
# https://mirror.chpc.utah.edu/pub/epel/7/x86_64/
# http://mirror.nexcess.net/epel/7/x86_64/
# http://mirror.cogentco.com/pub/linux/epel/7/x86_64/
# http://mirror.utexas.edu/epel/7/x86_64/
# http://mirror.unl.edu/epel/7/x86_64/
# https://pubmirror1.math.uh.edu/fedora-buffet/epel/7/x86_64/
# http://kdeforge2.unl.edu/mirrors/epel/7/x86_64/
# https://pubmirror2.math.uh.edu/fedora-buffet/epel/7/x86_64/
# http://reflector.westga.edu/repos/Fedora-EPEL/7/x86_64/
# https://dl.fedoraproject.org/pub/epel/7/x86_64/
# https://muug.ca/mirror/fedora-epel/7/x86_64/
# http://fedora.westmancom.com/epel/7/x86_64/
# http://mirror.its.dal.ca/pub/epel/7/x86_64/
# https://mirror.csclub.uwaterloo.ca/fedora/epel/7/x86_64/
# https://ca.mirror.babylon.network/epel/7/x86_64/ 
#
packages="pcre-devel-8.32-17.el7.x86_64.rpm
glib2-devel-2.54.2-2.el7.x86_64.rpm
ivykis-0.36.2-2.el7.x86_64.rpm
eventlog-0.2.13-4.el7.x86_64.rpm
libnet-1.1.6-7.el7.x86_64.rpm
syslog-ng-3.5.6-3.el7.x86_64.rpm"

# Format disk and create xfs LVM
echo -e "o\nw\n" | fdisk /dev/sdb
echo -e "n\np\n1\n\n\nw\n" | fdisk /dev/sdb
vgcreate syslog_ngvg /dev/sdb1
lvcreate -l 100%FREE -n syslog_nglv syslog_ngvg
mkfs.xfs /dev/syslog_ngvg/syslog_nglv

# Update local mount table
mkdir -p /opt/syslog-ng
echo '/dev/syslog_ngvg/syslog_nglv /opt/syslog-ng      xfs     defaults        0 0' >> /etc/fstab
mount /opt/syslog-ng

# Mount Splunk's syslog-ng repo
mount nfs-bde-dev.dev.mycorp.com:/mapr/BDEDev/splunk /mnt
#
echo "Installing ${packages}"
echo
grep 'nfs-bde-dev.dev.mycorp.com:/mapr/BDEDev/splunk' /proc/mounts >/dev/null
[[ "$?" != "0" ]] && {
  echo "Problem with mounting nfs-bde-dev.dev.mycorp.com:/mapr/BDEDev/splunk. Abort."
  exit
}
  
cd /mnt/syslog-ng.pkg && {
  for pkg in $packages
  do
    echo "Installing ${pkg}:"
    rpm -ivh $pkg
  done
}

# Now disable RHEL rsyslog
echo "Disable rsyslog"
service rsyslog stop
chkconfig rsyslog off

# Create /usr/lib/systemd/system/syslog-ng.service and symlink /etc/systemd/system/syslog.service
echo "Creating /usr/lib/systemd/system/syslog-ng.service and starting syslog-ng"
cat<<END>/usr/lib/systemd/system/syslog-ng.service
[Unit]
Description=System Logger Daemon
Documentation=man:syslog-ng(8)

[Service]
Type=notify
Sockets=syslog.socket
ExecStart=/usr/sbin/syslog-ng -F -p /var/run/syslogd.pid
ExecReload=/bin/kill -HUP \$MAINPID
StandardOutput=null
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=syslog.service
END

# Copy syslog.conf and its conf/*.conf to local /etc/syslog-ng/conf.d
cd /etc/syslog-ng && mv syslog-ng.conf syslog-ng.conf.ORIG
cd /mnt/syslog-ng.pkg/CONFIG/etc/syslog-ng && cp syslog-ng.conf /etc/syslog-ng
[[ ! -d /etc/syslog-ng/conf.d ]] && mkdir /etc/syslog-ng/conf.d
cd /mnt/syslog-ng.pkg/CONFIG/etc/syslog-ng/conf.d && \
find . -type f -name "*.conf"|cpio -pdmv /etc/syslog-ng/conf.d
cd / && umount /mnt

# Start/Enable syslog-ng 
systemctl start syslog-ng
systemctl enable syslog-ng
systemctl status syslog-ng
  
echo
cat<<END

NOTE:
1. Make sure RHEL package, nmap, is installed.

2. Run the command below to verify ports are in open state:
   nmap -n -PN -sT -sU -p- localhost|grep 514

3. To add additional port, create /etc/syslog-ng/${app}.conf, then on server
   systemctl reload syslog-ng 
   Then run 2. to verify ports open.
   NOTE: Follow the link when creating new TCP/UDP ports:
   https://bitbucket.mycorp.com/projects/AD00203364/repos/tos_syslog/browse/conf.d/template.conf?at=refs%2Fheads%2Fprod 

4. Refer to https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.24/administration-guide/13
   or
   https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.16/administration-guide

5. To chek for syntax,
   syslog-ng -svf /etc/syslog-ng/syslog-ng.conf
   If returns nil, it's all good.

5. Red Button F5 LB:
   - DEV: splunk-syslog-dev.dev.mycorp.com
   - QA : splunk-syslog-qa.dev.mycorp.com
   - PROD: splunk-syslog.mycorp.com
   - DC4: splunk-syslog-loc5.mycorp.com
   
END

