#!/bin/ksh
[[ `uname -n` = "ser15000some_loc" ]] && {
   echo "Running $0 on wrong node: ser15000some_loc"
   exit
}

{
# Install latest Java
umount /mnt 2>/dev/null
mount share_server.dev.mycorp.com:/infra/loc /mnt
#rpm -ivh /mnt/Java/JDK-1.8-Latest-Linux64.rpm
umount /mnt 2>/dev/null

# Install additional packages as required by METs
#os-update -ay install kernel-headers
#os-update -y install glibc-headers
#os-update -y install gcc
#os-update -y install gdb
#os-update -y install zip
#os-update -y install unzip
#rpm -q kernel-headers glibc-headers gcc gdb zip

# Set up splunk parameters
# 1. /etc/security/limits.conf
mv -f /etc/security/limits.conf /etc/security/limits.conf.ORIG
{
cat /etc/security/limits.conf.ORIG
cat<<END_
# Begin Splunk Settings
*     soft    nofile  262144
*     hard    nofile  262144
# End Splunk Settings
END_
}>/var/tmp/limits.$$

mv -f /var/tmp/limits.$$ /etc/security/limits.conf

# 2. /etc/sysctl.conf
mv -f /etc/sysctl.conf /etc/sysctl.conf.ORIG
{
cat /etc/sysctl.conf.ORIG
cat<<END__
# Begin Splunk Settings
fs.file-max = 2048000
# End Splunk Settings
END__
} > /var/tmp/sysctl.conf.$$

mv -f /var/tmp/sysctl.conf.$$ /etc/sysctl.conf
sysctl -p

# 3. /etc/security/limits.d/20-nproc.conf: nproc set to 131072 per Splunk's recommendation.
echo
echo "Updating /etc/security/limits.d/20-nproc.conf"
{
cat<<END
# Default limit for number of user's processes to prevent
# accidental fork bombs.
# See rhbz #432903 for reasoning.

*          soft    nproc     131072
*          hard    nproc     131072
root       soft    nproc     unlimited
END
} > /etc/security/limits.d/20-nproc.conf

chmod 644 /etc/security/limits.d/20-nproc.conf


# On RHEL6/7, Splunk recommends to turn off Transparent Huge Pages (THP).

[ -f /etc/rc.d/rc.local ] && {
  /bin/cp -p /etc/rc.d/rc.local /etc/rc.d/ORIG.rc.local
  {
    cat /etc/rc.d/ORIG.rc.local
    cat<<EOF

# On RHEL6/7, Splunk recommends to turn off Transparent Huge Pages (THP). 
# This has a profound impact on system load. There's a decent Oracle Blog 
# about it at 
# https://blogs.oracle.com/linux/entry/performance_issues_with_transparent_huge. 
# http://answers.splunk.com/answers/112305/on-rh-6-and-splunk-6-my-searches-are-consuming-lots-of-cpu
echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo never > /sys/kernel/mm/transparent_hugepage/defrag

EOF
  } > /var/tmp/rc.local.$$
/bin/mv -f /var/tmp/rc.local.$$ /etc/rc.d/rc.local
chmod +x /etc/rc.d/rc.local
/etc/rc.d/rc.local
}

} | tee /var/tmp/initial_splunk_setup.OUT
