#!/bin/bash
#############################################################################
# Setting up coredump in case needed for Splunk Troubleshooting"
# https://access.redhat.com/solutions/56021
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-abrt
# Note:
#   1. Core dump file size is set in /etc/abrt/abrt.conf:
#      Set MaxCrashReportsSize = 30000
#          DumpLocation = /opt/splunkindex_data/abrt
#   2. In /etc/abrt/abrt-action-save-package-data.conf
#      Set OpenGPGCheck = no
#          ProcessUnpackaged = yes
#   3. In /etc/abrt/plugins/CCpp.conf
#      Set MakeCompatCore = yes
#   4. To generate a coredump,
#      pgrep splunkd
#      kill -SIGABRT ${All_splunkd}
#      For example:
#      [root@s0181loc3 abrt]# pgrep splunkd
#      194203
#      194271
#      194521
#      [root@s0181loc3 abrt]# kill -SIGABRT 194203 194271 194521
#      Core Dump Output:
#      [root@s0181loc3 abrt]# pwd
#      /opt/splunkindex_data/abrt
#      [root@s0181loc3 abrt]# du -hs *
#      1.3G    ccpp-2022-10-10-11:27:24-194203
#      4.0K    last-ccpp
#############################################################################
# Written by user1 | Team
#
echo "Verifying abrt abrt-addon-ccpp abrt-tui"
yum -y install abrt abrt-addon-ccpp abrt-tui
echo
rpm -q abrt abrt-addon-ccpp abrt-tui
echo 
echo "Install ccpp hooks"
abrt-install-ccpp-hook install
abrt-install-ccpp-hook is-installed
echo "EXIT_status=$?"
echo "Modifying /etc/abrt/abrt-action-save-package-data.conf"
sed -i -e 's/ProcessUnpackaged = no/ProcessUnpackaged = yes/g' \
     -e 's/OpenGPGCheck = yes/OpenGPGCheck = no/g' \
        /etc/abrt/abrt-action-save-package-data.conf
echo
echo "Verifying OpenGPGCheck and ProcessUnpackaged in /etc/abrt/abrt-action-save-package-data.conf"
egrep '^OpenGPGCheck|^ProcessUnpackaged' /etc/abrt/abrt-action-save-package-data.conf
echo
echo "Modifying /etc/abrt/plugins/CCpp.conf: MakeCompatCore = no to yes"
sed -i 's/MakeCompatCore = no/MakeCompatCore = yes/g' /etc/abrt/plugins/CCpp.conf
echo "Verifying /etc/abrt/plugins/CCpp.conf:"
grep '^MakeCompatCore' /etc/abrt/plugins/CCpp.conf
echo
echo "/etc/abrt/abrt.conf, changing MaxCrashReportsSize to 30GB and DumpLocation = /opt/splunkindex_data/abrt"
sed -i -e 's/MaxCrashReportsSize = 5000/MaxCrashReportsSize = 30000/g' \
    -e '/#DumpLocation =/a DumpLocation = /opt/splunkindex_data/abrt' /etc/abrt/abrt.conf
echo "Verifying /etc/abrt/abrt.conf:"
egrep '^MaxCrashReportsSize|^DumpLocation' /etc/abrt/abrt.conf
echo
echo "starting abrtd.service"
systemctl start abrtd.service
echo "starting abrt-ccpp.service"
systemctl start abrt-ccpp.service

echo "verifying abrtd.service"
systemctl status abrtd.service|grep 'Active'
echo
echo "verifying abrt-ccpp.service"
systemctl status abrt-ccpp.service|grep 'Active'

echo "Enable  Autoreporting feature"
abrt-auto-reporting enabled
