#!/bin/bash
date_=`date '+%Y%m%d'`
bold_yellow="\e[1m\e[33m"
green=$(tput setaf 2)
red=$(tput setaf 1)
reset_color="\e[0m"
users_list="user1@mycorp.com,user2@mycorp.com,user4@mycorp.com,user3@mycorp.com,SivaKumar.Nakka@mycorp.com"

echo -en "Enter ${bold_yellow}CRQ${reset_color}#? "
read CRQ
[[ ! -s ~/CURRENCY_PATCHING/${CRQ} ]] && echo "~/CURRENCY_PATCHING/${CRQ} is empty. Abort" && exit

echo -en "Enter AD ${bold_yellow}first.last${reset_color}? "
read ad_uid
{
echo
echo "$(date): $ad_uid"
echo

if [[ -f ~/CURRENCY_PATCHING/${CRQ} ]]
then
   servers_list=`cat ~/CURRENCY_PATCHING/${CRQ}`
   echo
   echo "${CRQ}: re-enable_splunk on servers below:"
   echo "$servers_list"
   server_list_=`echo $servers_list|sed 's/ /,/g'`
   echo
   jldsh -ew ${server_list_} "re-enable_splunk"
else
   echo "~/CURRENCY_PATCHING/${CRQ} doesnot exist"
fi
echo
echo "Verifying splunkd on All servers. Please wait"
sleep 2
jldsh -ew ${server_list_} "pgrep splunkd|wc -l"
} | tee  ~/CURRENCY_PATCHING/LOG/${CRQ}_re-enable_splunk.${date_}

mailx -s "Post Patching Remedy Ticket: ${CRQ} re-enable_splunk Status" ${users_list} < ~/CURRENCY_PATCHING/LOG/${CRQ}_re-enable_splunk.${date_}
