#!/bin/bash
date_=`date '+%Y%m%d'`
bold_yellow="\e[1m\e[33m"
green=$(tput setaf 2)
red=$(tput setaf 1)
reset_color="\e[0m"
users_list="user1@mycorp.com,user2@mycorp.com,user4@mycorp.com,user3@mycorp.com,SivaKumar.Nakka@mycorp.com"


echo -en "Enter ${bold_yellow}CRQ${reset_color}#? "
read CRQ
[[ ! -s ~/CURRENCY_PATCHING/${CRQ} ]] && echo "~/CURRENCY_PATCHING/${CRQ} is empty. Abort" && exit

echo -en "Enter AD ${bold_yellow}first.last${reset_color}? "
read ad_uid

{
   echo
   echo "$(date): $ad_uid"
   echo
   servers_list=`cat ~/CURRENCY_PATCHING/${CRQ}`
   echo
   echo "${CRQ}: Offline splunkd on servers below:"
   echo "$servers_list"
   echo
   for node in $servers_list
   do
     ping -c1 $node |grep '100% packet loss' >/dev/null
     if [[ "$?" != "0" ]]
     then
        ssh -q $node "run_splunk_offline"
        echo
     else
        echo "$node is NOT pingable" 
     fi
   done
} | tee  ~/CURRENCY_PATCHING/LOG/${CRQ}.${date_}

mailx -s "Patching Remedy Ticket: ${CRQ} Splunk offline Status" ${users_list} < ~/CURRENCY_PATCHING/LOG/${CRQ}.${date_}
