#!/bin/bash
SPLUNK_LOCAL=/opt/splunk/etc/system/local
date_=`date '+%Y%m%d'`
cd ${SPLUNK_LOCAL} && {
  cp -f server.conf server.conf.${date_}
  sed '/^\[clustering/,/^pass4SymmKey/d' server.conf > server.conf.STAGE
  {
    cat <<END

[clustering]
master_uri = https://cud1-012706.us.global.mycorp.com:8089
mode = searchhead
multisite = true
pass4SymmKey = qacluster

END
  } >> server.conf.STAGE
  chown ser_act.dev:unx_9998_access server.conf.${date_} server.conf.STAGE
}
echo "updated ${SPLUNK_LOCAL}/server.conf --> server.conf.STAGE"
 

