#!/bin/bash
node=`uname -n`
hot=${node}.hot
cold=${node}.cold

cd /root/HDD && {
   line_no=`grep -n "Wed Jan 17 23:59:" $cold|tail -1|awk -F: '{print $1}'`
   # Delete from the 1st line to $line_no
   [[ -n "${line_no}" ]] && sed -i "1,${line_no}d" $cold
}

line_no=""
cd /root/SSD && {
   line_no=`grep -n "Wed Jan 17 23:59:" $hot|tail -1|awk -F: '{print $1}'`
   # Delete from the 1st line to $line_no
   [[ -n "${line_no}" ]] && sed -i "1,${line_no}d" $hot
}
