#!/bin/bash
Venafi_key='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSC1u+jhwVzlbpq33Pyvk6m4DHYnTN5WDEXYAuUUB+tM4Fe+ap5ob/MlIB3CqCqHIdy0IKyJ+kwdZqJFZdFYtt6r59SwL3SCGVupd+jYU3Fx1wfrnprKsWzqfGlKq83Tf7ExNynLZkF2OwxrQM5h0UZV7XR1ajSBUABiuOFkVqyFwewUXu52Yavzn4zGtuINk1iDHOUDFfgPAUUcxYbtajc2ovT19+2YpQ4tfl/4CRCtEIkCTYwu0VYgR+RjBHmQvHWSU9zZJMl9BykZljdyTvoD6cAUoetNWIifXmf4vFbkZIvYjFMAqs1Tl0VjwZSdxkA1mhnlRIsZVuIYKGpH0f'

cd /ssh-keys && {
   [[ -f root ]] && {
     cp root root.$$
     echo "${Venafi_key}" >> root
   }
}
