#!/bin/bash
CLUSTER=/usr/local/share/cluster/splunk.cluster
HECs="ser21-012454
ser21-012459
ser21-012461
ser21-012463
ser21-012457
ser21-012453
ser21-012462
ser21-012464
ser21e-003103
ser21e-003104
ser21e-003105
ser21e-003106
ser21f-003081
ser21f-003082
ser21f-003083
ser21f-003084
ser22-011219
ser22-011216
ser22-011221
ser22-011218
ser22-011222
ser22-011225
ser22e-003071
ser22e-003072
ser22e-003073
ser22e-003074
ser22f-003059
ser22f-003060
ser22f-003061
ser22f-003062
ser22-011226
ser22-011227
ser24-007714
ser24-007715
ser24-010340
ser24-010341
ser24-010342
ser24-010343
ser24-010344
ser24-010345
ser24-007716
ser24-007717
ser24-010331
ser24-010333
ser24-010334
ser24-010335
ser24-010336
ser24-010337"

{
date
echo "BEGIN:Taking Memory snap shot"
echo '                            total        used        free      shared  buff/cache   available'
echo '---------------------------------------------------------------------------------------------'
jldsh -ec $CLUSTER -eg All_HEC_Confluent_Enterprise_PCF_Kafka_Connect "free -h|grep ^Mem"
echo '---------------------------------------------------------------------------------------------'

for hec in $HECs
do
  /usr/local/bin/jldsh -ew $hec "systemctl restart Splunkd"
  echo "Restart_COMPLETE"
done

echo
date
echo "AFTER:Taking Memory snap shot"
echo '                            total        used        free      shared  buff/cache   available'
echo '---------------------------------------------------------------------------------------------'
jldsh -ec $CLUSTER -eg All_HEC_Confluent_Enterprise_PCF_Kafka_Connect "free -h|grep ^Mem"
echo '---------------------------------------------------------------------------------------------'
echo
} | mailx -s "PCF HECs Mem Usage" user1@mycorp.com,user3@mycorp.com
