#!/bin/ksh

hec=ser11142some_loc
token='0a3d6a83-349b-4a1d-aab8-a1bdb97c48f4'

eval `{
cat<<END
curl -k https://${hec}.some_loc.mycorp.com:8088/services/collector -H 'Authorization: Splunk ${token}' -d ' {"sourcetype": "thousandeyes", "event":"Test_TE! Test_TE! Test_TE!"}'
END
}`
