#!/bin/ksh
# nice -n 19 echo ./run_iotop|at now
date_=$(date '+%F_%H%M')
OUTPUT=/var/tmp/IOTOP/iotop.${date_}
# 4GB = 4294967296 bytes
SIZE_IN_BYTES=4294967296

# iter= in seconds
# If 4 hrs --> 14400 seconds
user_list="user1@mycorp.com,user2@mycorp.com,user3@mycorp.com"


[[ ! -d /var/tmp/IOTOP ]] && mkdir -p /var/tmp/IOTOP

# Running iotop in background for 4 hrs (14400 seconds)
nohup iotop -botqqqk --iter=14400 >>${OUTPUT} &
job_pid=$!
echo "${job_pid}" > /var/tmp/run_iotop.PID
echo "Background process id for the job: /var/tmp/run_iotop.PID: ${job_pid}"
echo "OUTPUT:${OUTPUT}"

while [ 1 ]
do
  # Checking the ${OUTPUT} filesize
  size=$(du -b ${OUTPUT}|awk '{print $1}')
  [[ ${size} -gt ${SIZE_IN_BYTES} ]] && {
    kill -9 ${job_pid}
    echo "Aborted job_pid ${job_pid} due to > ${SIZE_IN_BYTES} bytes"
    mailx -s "`uname -n`: run_iotop PID:$job_pid aborted due to ${OUTPUT} size: $size bytes > ${SIZE_IN_BYTES} bytes (EOM)" ${user_list} < /dev/null
    exit
  }
  sleep 5s
  lsof -p ${job_pid} >/dev/null
  [[ "$?" != "0" ]] && {
     mailx -s  "$(uname -n):`basename $0`: JobID ${job_pid} died (EOM)" user1@mycorp.com < /dev/null
     exit
  }
done
echo "OUTPUT:/tmp/IOTOP/iotop.${date_}"

