#!/bin/ksh
# NOTE: To run this script as a daemon
# nice -n 19 echo ./run_daily_strace|at now

date_=$(date '+%a%H%M_%m%d%Y')
HOT=/root/SSD
COLD=/root/HDD
# 2GB=2147483648 bytes
SIZE_IN_BYTES=2147483648
users_list="user1@mycorp.com,user2@mycorp.com"

[[ ! -d $HOT ]] && mkdir $HOT
[[ ! -d $COLD ]] && mkdir $COLD
[[ ! -d /opt/splunkindexhot_data/Splunk_Case_3114624 ]] && mkdir /opt/splunkindexhot_data/Splunk_Case_3114624

while [ 1 ]
do
  # Splunk cold /opt/splunkindex_data
  {
    cd /opt/splunkindex_data/Splunk_Case_3114624 && strace -T -y  -e trace=writev,write ./test_io
  } > /tmp/cold 2>&1
 
  {
    cat /tmp/cold | \
    while read line
    do 
      echo "`date`: $line"
    done
  } >> ${COLD}/`uname -n`.cold 2>&1

  # Splunk cold /opt/splunkindex_data
  {
    cd /opt/splunkindexhot_data/Splunk_Case_3114624 && strace -T -y  -e trace=writev,write ./test_io
  } >/tmp/hot 2>&1

  {
    cat /tmp/hot | \
    while read line
    do
      echo "`date`: $line"
    done
  } >> ${HOT}/`uname -n`.hot 2>&1
  sleep 3s
  splunk_cold_file_size=$(du -b ${COLD}/`uname -n`.cold|awk '{print $1}')
  splunk_hot_file_size=$(du -b ${HOT}/`uname -n`.hot|awk '{print $1}')
  total_hot_cold_size=`expr ${splunk_cold_file_size} + ${splunk_hot_file_size}`
  [[ ${total_hot_cold_size} -gt ${SIZE_IN_BYTES} ]] && {
    echo "File size ${COLD}/`uname -n`.cold ($splunk_cold_file_size bytes) AND ${HOT}/`uname -n`.hot  ($splunk_hot_file_size bytes) > ${SIZE_IN_BYTES}. Abort" \
    | mailx -s "`uname -n`: run_daily_strace aborted." ${users_list}
    exit
  }
  
done
