#!/bin/ksh
date_=`date '+%Y%m%d'`
PATH=/usr/local/bin:$PATH
CLUSTER=/usr/local/share/cluster/splunk.cluster
set -o allexport

[[ ! -d /root/DAILY_REPORT ]] && mkdir -p /root/DAILY_REPORT
# Core SH cluster
{
# The jldsh below will clean up /opt/splunk/etc/[users/apps] large lookups as of 11/22/2021.
jldsh -eg All_splunk_CORE_multisite_SH -c $CLUSTER "clean_snapshot_dispatch -list"|dshbak
} >> /root/DAILY_REPORT/CORE_SH_cluster.${date_}.rpt

# ES SH cluster
#{
#jldsh -eg splunk_ES_SH  -c $CLUSTER "clean_snapshot_dispatch_ES -list"|dshbak
#} >> /root/DAILY_REPORT/ES_SH_cluster.${date_}.rpt
