#!/bin/ksh
while [ 1 ]
do
i=$((i + 1))
cd /opt/splunk/var/run/splunk/dispatch; grep -r --include='search.log*' -lZ "ERROR HttpClientRequest - HTTP client error: Connection closed by peer" | xargs -r --null -I{} sh -c 'touch $(dirname {})/save'

sleep 180
echo i=$i
done

