#!/bin/bash
pgrep splunkd >/dev/null 2>&1
[[ "$?" != "0" ]] && echo "splunkd is not running. exit" && exit
nohup splunk_offline & >/dev/null

job_pid=$!
echo "${job_pid}" > /var/tmp/splunk_offline.PID

while [ 1 ]
do
  echo "$(uname -n): splunk_offline is in progress (PID:${job_pid}). Please wait"
  lsof -p ${job_pid} >/dev/null
  [[ "$?" != "0" ]] && {
     echo "$(uname -n): splunk_offline (PID:${job_pid}) COMPLETED."
     exit
  }
  sleep 1m
done
