#!/bin/bash
All_PDC13="PDC1_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC1_Kafka_PCF_Metrics_Mobile_Logs_F-core,PDC3_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC3_Kafka_PCF_Metrics_Mobile_Logs_F-core"

enter_option ()
{
           cat<<END

PDC[1]
PDC[3]
Both PDC1/3 [13]
DC[4]

END
         echo -n "Enter [1|3|13|4]? "
         read number
}

while :
do
echo
echo
cat<<END
####################################################################
PROD Kafka Sink Connector for PCF Metrics.

C) Check Status
D) Disable and Stop connect-distributed.service
E) Enable and Start connect-distributed.service
Q)uit

####################################################################

END
echo -n "Enter option [C|D|E|Q]? "
read option

case $option in
   C|c )
         enter_option
         case ${number} in
              1 )
                 jldsh -eg PDC1_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC1_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl status connect-distributed |grep Active"
                 ;;
              3 )
                 jldsh -eg PDC3_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC3_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl status connect-distributed |grep Active"
                 ;;
             13 )
                 jldsh -eg ${All_PDC13} "systemctl status connect-distributed |grep Active"
                 ;;
              4 )
                 jldsh -eg DC4_Kafka_PCF_Metrics_Mobile_Logs_E-core,DC4_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl status connect-distributed |grep Active"
                 ;;
              * )
                 echo "Wrong option. Try again."
                 break
                 ;;
         esac
         ;;
   
   D|d )
         enter_option
         case ${number} in
              1 )
                 jldsh -eg PDC1_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC1_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl disable connect-distributed;systemctl stop connect-distributed"
                 ;;
              3 )
                 jldsh -eg PDC3_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC3_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl disable connect-distributed;systemctl stop connect-distributed"
                 ;;
             13 )
                 echo
                 jldsh -eg ${All_PDC13} "systemctl disable connect-distributed;systemctl stop connect-distributed;echo;systemctl status connect-distributed|grep Active"
                 echo
                 ;;
              4 )
                 jldsh -eg DC4_Kafka_PCF_Metrics_Mobile_Logs_E-core,DC4_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl disable connect-distributed;systemctl stop connect-distributed"
                 ;;
              * )
                 echo "Wrong option. Try again."
                 break
                 ;;
         esac
         ;;
   E|e )

         enter_option
         case ${number} in
              1 )
                 jldsh -eg PDC1_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC1_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl enable connect-distributed;systemctl start connect-distributed"
                 ;;
              3 )
                 jldsh -eg PDC3_Kafka_PCF_Metrics_Mobile_Logs_E-core,PDC3_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl enable connect-distributed;systemctl start connect-distributed"
                 ;;
             13 )
                 echo
                 jldsh -eg ${All_PDC13} "systemctl enable connect-distributed;systemctl start connect-distributed;sleep 2;systemctl status connect-distributed|grep Active"
                 echo
                 ;;
              4 )
                 jldsh -eg DC4_Kafka_PCF_Metrics_Mobile_Logs_E-core,DC4_Kafka_PCF_Metrics_Mobile_Logs_F-core "systemctl enable connect-distributed;systemctl start connect-distributed"
                 ;;
              * )
                 echo "Wrong option. Try again."
                 break
                 ;;
         esac
         ;;

   Q|q )
         exit
         ;;
esac
done
