#!/bin/bash
###############################################################################
# Refer to
# https://community.splunk.com/t5/Deployment-Architecture/Using-REST-API-load-balancing-in-a-Search-Head-Cluster-why-are/m-p/262272
###############################################################################
bold_yellow="\e[1m\e[33m"
reset_color="\e[0m"

get_sessionKey ()
{
  sessionKey=$(
  {
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/auth/login -d username=${user} -d password=$key
  } 2>/dev/null | grep sessionKey|awk -F'<sessionKey>|</sessionKey>' '{print $2}')
}

get_sid ()
{
  sid=$(
  {
#index=_internal host IN (s3140some_loc,s3141some_loc,s3142some_loc,s0166loc3,s0167loc3,s3146some_loc,s3147some_loc,s3148some_loc,s3140loc2,s3141loc2,s3145loc2,s3146loc2) "*QUEUED reason\=\"The maximum number of concurrent historical searches on this instance has been reached*"
#| stats count by host
#"*QUEUED reason\=\"The maximum number of concurrent historical searches on this instance has been reached*"

#  curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=_internal sourcetype=splunkd host IN (s3140some_loc,s3141some_loc,s3142some_loc,s0166loc3,s0167loc3,s3146some_loc,s3147some_loc,s3148some_loc,s3140loc2,s3141loc2,s3145loc2,s3146loc2) "*QUEUED reason\=\"The maximum number of concurrent historical searches on this instance has been reached*" | stats count by host" -d earliest_time="-60m@m" -d latest_time="-0m@m" 

   #curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=secops*|stats count by splunk_server|head" -d earliest_time="-15m@m" -d latest_time="-0m@m"
#  curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=assettransfermanagement sourcetype="*secure_elilogs*"|stats count by host|head" -d earliest_time="-2m@m" -d latest_time="-0m@m"
   #curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=mycorpcom cf_app_name=mycorp-cet-capability-transfers-api* (sourcetype=mycorp-cet-capability-transfers-api-blue_secure_elilogs OR sourcetype=mycorp-cet-capability-transfers-api-green_secure_elilogs OR sourcetype=mycorp-cet-capability-transfers-api_secure_elilogs OR sourcetype=elilogs) (msg.Service.URL=http://transfersapi.mycorp.com/api/transfer/ach) msg.Results.Message=Success | rename Actor.Cust as cs_username | spath msg |stats count by msg" -d earliest_time="-2m@m" -d latest_time="-0m@m"
  #  curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=_internal|stats count by splunk_server | head" -d earliest_time="-2m@m" -d latest_time="-0m@m"

#  curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=sne sourcetype=sne_SACD_elilogs | spath %22Info.InfoMessage.MessageType%22 | search %22Info.InfoMessage.MessageType%22=CheckImageRecoService|stats count by splunk_server" -d earliest_time="-15m@m" -d latest_time="-0m@m"

#  curl -k -u ${user}:${key} https://${node_fqdn}:8089/servicesNS/svc.bdh_curator_prod/SCH_VoiceSearchApp_app/search/jobs/export -d search="savedsearch NARLogExport" -d earliest_time="-15m@m" -d latest_time="-0m@m"


   curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=_internal |stats count by splunk_server " -d earliest_time="-5m@m" -d latest_time="-0m@m"
  } 2>/dev/null | grep 'sid'|awk -F'<sid>|</sid>' '{print $2}')
}

get_dispatchState ()
{
  dispatchState=$(
  {
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs/$1
  } 2>/dev/null | grep 'dispatchState'|awk -F'">|</' '{print $2}')
}

get_results ()
{
  echo -e "sid=${bold_yellow}${1}${reset_color}"
  results=$(
  {
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs/${1}/results --get -d output_mode=csv
    #curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs/${1}/results --get -d output_mode=json -d count=5|jq
  } 2>/dev/null )
}

show_SH_list ()
{
cat<<END

Here's list of PROD ResAPI Search Heads:

ser21-010907: 3BD7E8F9-913F-4953-B815-2BA049C2AFF7
ser21-010908: DE015196-AEDE-40B4-96C6-E228F3151BCF
ser21-010909: C98CED76-1635-4588-8B06-CC2B97B408F1
ser21-010910: 519E74A6-7DB5-4073-AF03-D5753220E480
ser24-009707: B689B22C-C76B-4033-A033-46C690CFB677
ser24-009708: E0C451E7-1A2E-4C3C-87DA-F9EE09701152
ser24-009706: 33550D56-E93E-4FCC-B3C6-78AFED7329DD

END
read -p "Enter search head name or F5 (splunk-restapi.mycorp.com)? " node
}

##########
# M A I N
##########
echo -en "Enter your ${bold_yellow}first.last${reset_color}: "
read user
read -sp "Password: " key
#read -p "Password: " key

show_SH_list

while [ 1 ]
do
  echo $node|grep -q 'mycorp'
  if [[ "$?" = "0" ]]
  then
   node_fqdn=$node
  else
     node_fqdn=$(host ${node}|awk '{print $1}')
  fi
  echo "Authenticating ${user} via ${node}: "
  get_sessionKey
  [[ -z ${sessionKey} ]] && echo "User: ${user} | Authentication failed. Abort" && exit
  
  echo "sessionKey=${sessionKey}"
  echo
  echo "Running search and getting sid ...."

  get_sid
  [[ -z "${sid}" ]] && echo "sid is NOT_DEFINED." && break 
  echo -en "sid=${bold_yellow}${sid}${reset_color}"
  echo
  echo -e "Retrieve ad-hoc search status with sid: ${bold_yellow}${sid}${reset_color}"
  get_dispatchState ${sid}
  echo dispatchState=${dispatchState}
  total_secs=""
  while [[ "${dispatchState}" != "DONE" ]] 
  do
    #echo "let's wait for 10 seconds ..."
    get_dispatchState ${sid}
    sleep 1s
    total_secs=`expr $total_secs + 1`
    echo "${total_secs}s dispatchState=${dispatchState}"
  done
  echo "Total secs: $total_secs"
  echo
  echo "Getting results ..."
  echo
  get_results ${sid}
  echo "results=`echo ${results}|head -1`"
  echo

  read -p "Try again with F5 LB $node (Y|N)? " ans
  case $ans in
       Y|y )
            show_SH_list
            ;;
         * )
            echo "Good Bye"
            exit
            ;;
    esac
done
