#!/bin/bash

# According to Splunk Best Practice by Splunk's Manu Jose, Yuan Xu Sr. Software Engineer
# Rolling restart from the captain maintains the node as captain after restarts
UID_="ser_act.prod"

echo -n "Enter a SH nodename? "
read search_head

# Identify all members in the cluster
{
eval `gpg --batch --xyz xyz -quiet --no-verbose -d /.splunk` >/dev/null 2>&1
} 2>/dev/null


echo "Below are all members in $search_head SH cluster:"
ssh ${search_head} "su - ${UID_} -c \"/opt/splunk/bin/splunk show shcluster-status -auth admin:${prod}\"" 2>/dev/null|grep label|awk '{print $NF}'|sort|uniq


all_search_heads=`ssh ${search_head} "su - ${UID_} -c \"/opt/splunk/bin/splunk show shcluster-status -auth admin:${prod}\"" 2>/dev/null|grep label|awk '{print $NF}'|sort|uniq`
#all_search_heads=$(curl -k -u admin:${prod} https://${captain}:8089/services/shcluster/captain/members 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g')
echo all_search_heads=${all_search_heads}

# 
[[ -z "${all_search_heads}" ]] && {
   echo "${search_head}, is splunkd down? Operation Abort."
   exit
}

# Identify captain
captain=`ssh ${search_head} "su - ${UID_} -c \"/opt/splunk/bin/splunk list shcluster-members -auth admin:${prod}\"" 2>/dev/null|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}'`
echo captain=$captain
# Check captain splunk version
splunk_version=`ssh $captain "/opt/splunk/bin/splunk -version|awk '{print $2}'" 2>/dev/null`
echo
echo "Captain Splunk version: $splunk_version"

# Initiate rolling restart from the captain.
echo "Initiate rolling restart from the captain, $captain"
#ssh $captain  "su - ${UID_} -c \"/opt/splunk/bin/splunk rolling-restart shcluster-members -searchable true -auth admin:${prod}\"" 2>/dev/null
ssh $captain  "su - ${UID_} -c \"/opt/splunk/bin/splunk rolling-restart shcluster-members -auth admin:${prod}\"" 2>/dev/null

#NOTE: Can also be done via restAPI call BUT NOT fully tested
#$(curl -k -u admin:${key} https://$captain:8089/services/shcluster/config -d rolling_restart=searchable -d decommission_search_jobs_wait_secs=300

captain=`echo $captain|sed 's/.some_loc.mycorp.com//g'`
echo "Now you can check status via"
echo "watch -n10 /opt/splunk/bin/splunk rolling-restart shcluster-members -status 1 -auth admin:${prod} on $captain"

