#!/bin/ksh
##############################################################################
# This script checks the "tasks.max": "9" defined in start_connector         #
# Refer to https://confluence.mycorp.com/display/TOS/Splunk+Connect+for+Kafka#
##############################################################################
# user1 P. user1 | T O S Platform A
#
users_list="user1@mycorp.com,user2@mycorp.com"
users_list="user1@mycorp.com"
env_=`uname -n|grep -o '...$'`

case ${env_} in
   loc2 )
        connector_name=kafka-topic-loc2-geneos-raw.table
        ;;
   some_loc )
        connector_name=kafka-topic-some_loc-geneos-raw.table
        ;;
esac

curl --insecure https://$(uname -n):8443/connectors/${connector_name}/status|jq '.[]'|grep "RUNNING"

num=`{
curl --insecure https://$(uname -n):8443/connectors/${connector_name}/status
}|jq '.[]'|grep "RUNNING"|wc -l`

#case $num in
#      10 )
#          echo "Number of Tasks: $num"
#          echo "All is good."
#          ;;
#       * )
#          {
#            curl --insecure https://$(uname -n):8443/connectors/${connector_name}/status
#            echo
#            curl --insecure https://$(uname -n):8443/connectors/${connector_name}/status | jq '.[]'|grep "RUNNING"
#          } | mailx -s "Problem with `uname -n` Kafka Connector" ${users_list}
#          ;;
#esac

