#!/bin/ksh
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               gid=unx_60231_splunk_admin_dev
               key=${dev}
               ;;
   some_loc | loc2 ) uid=ser_act.prod
               gid=unx_9998_access
               key=${prod}
               ;;
           * )
               case `uname -n` in
                   ser2* ) uid=ser_act.prod
                           gid=unx_9998_access
                           ;;
                   cud*| cut* ) uid=ser_act.dev
                                  gid=unx_60231_splunk_admin_dev
                           ;;
               esac
               ;;
esac
echo
su - ${uid} -c "${SPLUNK_BIN}/splunk list tcp 9990 -auth admin:${key}"

