#!/bin/bash
###############################################################################
# Refer to
# https://community.splunk.com/t5/Deployment-Architecture/Using-REST-API-load-balancing-in-a-Search-Head-Cluster-why-are/m-p/262272
###############################################################################
bold_yellow="\e[1m\e[33m"
reset_color="\e[0m"

get_sessionKey ()
{
  sessionKey=$(
  {
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/auth/login -d username=${user} -d password=$key
  } 2>/dev/null | grep sessionKey|awk -F'<sessionKey>|</sessionKey>' '{print $2}')
}

get_sid ()
{
  sid=$(
  {
#   curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=mycorpcom cf_app_name=mycorp-cet-capability-transfers-api* (sourcetype=mycorp-cet-capability-transfers-api-blue_secure_elilogs OR sourcetype=mycorp-cet-capability-transfers-api-green_secure_elilogs OR sourcetype=mycorp-cet-capability-transfers-api_secure_elilogs OR sourcetype=elilogs) (msg.Service.URL=http://transfersapi.mycorp.com/api/transfer/ach) msg.Results.Message=Success | rename Actor.Cust as cs_username | spath msg |stats count by msg" -d earliest_time="-2m@m" -d latest_time="-0m@m"
#    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=_internal|stats count by splunk_server | head" -d earliest_time="-2m@m" -d latest_time="-0m@m"
#   curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs -d search="search index=_internal host=s0196loc3|stats count by splunk_server " -d earliest_time="-4h@h" -d latest_time="-0h@h"
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/servicesNS/-/-/saved/searches
  } 2>/dev/null | grep 'sid'|awk -F'<sid>|</sid>' '{print $2}')
}

get_dispatchState ()
{
  dispatchState=$(
  {
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs/$1
  } 2>/dev/null | grep 'dispatchState'|awk -F'">|</' '{print $2}')
}

get_results ()
{
  echo -e "sid=${bold_yellow}${1}${reset_color}"
  results=$(
  {
    curl -k -u ${user}:${key} https://${node_fqdn}:8089/services/search/jobs/${1}/results --get -d output_mode=csv
  } 2>/dev/null )
}

show_SH_list ()
{
cat<<END

Here's list of PROD ResAPI Search Heads:
ser21-010907
ser21-010908
ser21-010909
ser21-010910
ser24-009707
ser24-009708
ser24-009706

END
read -p "Enter search head name or F5 (splunk-restapi.mycorp.com)? " node
}

##########
# M A I N
##########
echo -en "Enter your ${bold_yellow}first.last${reset_color}: "
read user
read -sp "Password: " key

show_SH_list

while [ 1 ]
do
  echo $node|grep -q 'restapi'
  if [[ "$?" = "0" ]]
  then
   node_fqdn=$node
  else
     node_fqdn=$(host ${node}|awk '{print $1}')
  fi
  echo "Authenticating ${user} via ${node}: "
  get_sessionKey
  [[ -z ${sessionKey} ]] && echo "User: ${user} | Authentication failed. Abort" && exit
  
  echo "sessionKey=${sessionKey}"
  echo
  echo "Running search and getting sid ...."

  get_sid
  echo -en "sid=${bold_yellow}${sid}${reset_color}"
  echo
  echo -e "Retrieve ad-hoc search status with sid: ${bold_yellow}${sid}${reset_color}"
  get_dispatchState ${sid}
  echo dispatchState=${dispatchState}

  while [[ "${dispatchState}" != "DONE" ]] 
  do
    echo "let's wait for 10 seconds ..."
    sleep 10s
    get_dispatchState ${sid}
    echo dispatchState=${dispatchState}
  done
  echo
  echo "Getting results ..."
  echo
  get_results ${sid}
  echo "results=`echo ${results}|head -1`"
  echo

  read -p "Try again with F5 LB splunk-restapi.mycorp.com (Y|N)? " ans
  case $ans in
       Y|y )
            node=splunk-restapi.mycorp.com
            continue
            ;;
         * )
            echo "Good Bye"
            exit
            ;;
    esac
done
