#!/bin/ksh
env_=`uname -n|grep -o '...$'`

{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               key=$dev
               ;;
   some_loc | loc2 | loc3 ) uid=ser_act.prod
               key=$prod
               ;;
           * )
               case `uname -n` in
                   ser2* ) uid=ser_act.prod
                           gid=unx_9998_access
                           key=$prod
                           ;;
                   cud*| cut* ) uid=ser_act.dev
                                  gid=unx_60231_splunk_admin_dev
                                  key=$dev
                           ;;
               esac
               ;;
esac

captain=`su - ${uid} -c "/opt/splunk/bin/splunk list shcluster-members -auth admin:${key}|grep -A1 'is_captain:1'|tail -1"|awk -F: '{print $2}'`
echo "$captain"
