#!/bin/ksh

####################################################
#                                                  #
#  $Id: show_splunkforwarder,v 1.0 2011/06/11 Exp $#
#  Show Splunk Forwarder Processes                 #
#  Authors: Carlos R. Martinez                     #
#                                                  #
####################################################

uname -sn |read OS SERVER
PROG_NAME=${0##*/}
REV="1.0"
REV="$Revision: 1.0 $"
REV=${REV%$}      # strip the last $
DATE=`date "+%a %d %H:%M %Y"`

case $OS in

   Linux)   GREP="grep"
   ;;

esac

## Processes

#SPLUNK_process=`ps -eo euser,pid,etime,pcpu,pmem,args | ${GREP} "^[r]oot" | ${GREP} -i "splunkd" | $GREP -v $GREP`
SPLUNK_process=`ps -eo euser,pid,etime,pcpu,pmem,args |  ${GREP} -i "splunkd" | $GREP -v $GREP`

##

check() {

  echo "# $DATE $PROG_NAME: version: $REV"
  echo
  echo "# $PROG_NAME for $SERVER:"
  printf '%-15s %-10s %-6s %-7s %-22s %-4s %-4s\n' "# Process" "Status" "USER" "PID" "Age(dd-hh:mm:ss)" "%CPU" "%MEM"

  if [[ ! -z $SPLUNK_process ]]; then
    echo "${SPLUNK_process}" | while read euser pid etime cpu mem args
    do
      printf '%-15s %-10s %-6s %-10s %-20s %-4s %-4s\n' "# splunkd:" "UP" "${euser}" "${pid}" "${etime}" "${cpu}" "${mem}"
    done
  else
    printf '%-15s %-10s\n' "# splunkd:" "DOWN"
  fi
  echo
}

tivoli() {

if [[ ! -z  $SPLUNK_process ]]; then
  echo "OK"
  printf '%-3s %-1s %-10s\n' "OK" "|" "splunkd"
else
  echo "BAD"
  printf '%-3s %-1s %-10s\n' "BAD" "|" "splunkd" 
fi

}

check_default() {

 print "$DATE $PROG_NAME: version: $REV\n"
 print "$PROG_NAME for $SERVER:"
 printf '%-15s %-10s\n' "Process" "Status"


  ## SPLUNK
  if [[ ! -z $SPLUNK_process ]]; then
    printf '%-15s %-10s\n' "SPLUNK:" "UP"
  else 
    printf '%-15s %-10s\n' "SPLUNK:" "DOWN"
  fi
}

usage() {

cat<<++
Invalid Option!!!
USAGE:  show_splunkforwarder [-s]|[-t]

  where
        -s = shows splunk forwarder status, euser, pid, age(etime), %cpu & %mem
        -t = shows splunk forwarder status for Tivoli

++

}

options() {

   case $1 in
      -s) check;; 
      -t) tivoli;; 
       *) usage;;
   esac

}

if [ $# -eq 0 ]
then
   check_default
elif [ $# -eq 1 ]
then
   options $1
fi
