#!/bin/ksh
case $1 in
  -m )
       ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%mem|head
       ;;
  -c )
       ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu|head
       ;;
   * )
       cat<<END

Usage: $0 [-m|-c]

END
       exit
       ;;
esac
