#!/bin/bash
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
bold_yellow="\e[1m\e[33m"
green=$(tput setaf 2)
red=$(tput setaf 1)
reset_color="\e[0m"
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               key=${dev}
               ;;
   some_loc | loc2 | loc3 | loc4 ) uid=ser_act.prod
               key=${prod}
               ;;
           * )
               case `uname -n` in
                   ser2* ) uid=ser_act.prod
                          key=${prod}
                           ;;
                   cud*| cut* ) uid=ser_act.dev
                                key=${dev}
                           ;;
               esac
               ;;
esac

# Is this SHC captain?
captain=`su - ${uid} -c "/opt/splunk/bin/splunk list shcluster-members -auth admin:${key}|grep -A1 'is_captain:1'|tail -1"|awk -F: '{print $2}'`
echo "$captain" | grep `uname -n` >/dev/null
if [[ "$?" = "0" ]]
then
    echo
    su - ${uid} -c "${SPLUNK_BIN}/splunk rolling-restart shcluster-members -status 1 -auth admin:${key}"
else
    echo -e "Run `basename $0` on Search Head Captain, ${bold_yellow}${captain}${reset_color}, ONLY"
    exit
fi

