#!/bin/bash
####################################################################################
# splunk_offline on index multisite cluster is based on
# https://docs.splunk.com/Documentation/Splunk/9.0.3/Indexer/Takeapeeroffline
# Tasks perform:
# 1. Disable Splunkd.service at boot time
# 2. Running su - ${uid} -c "/opt/splunk/bin/splunk offline as service account
# 3. Wait for 5 secs to ensure splunkd is no longer spawned via Restart=always
#    defined in Splunkd.service
#    - If true stop splunkd via `systemctl stop Splunkd`
####################################################################################
# user_ | T O S Platform Splunk
# Splunk Service account:
#ser_act.prod:VAS:500327:9998:ser_act.prod:/ser_act.prod:/bin/ksh
#ser_act.dev:VAS:562314:60231:ser_act.dev:/ser_act.dev:/bin/ksh
date_=$(date '+%a%H%M_%m%d%Y')
env_=`uname -n`
typeset -R3 env_
TOS_splunk_team="user1@mycorp.com,user2@mycorp.com,user4@mycorp.com,user3@mycorp.com,SivaKumar.Nakka@mycorp.com,bharat.devagiri@mycorp.com,thirumalesh.vanguri@mycorp.com,ramakrishna.manthri@mycorp.com,madhusudhanreddy.ettedi@mycorp.com"


wait_5s ()
{
  dots_=". . . . ."
  echo -n "Let's wait for 5 seconds to make sure splunkd is down "
  for dot in $dots_
  do
    echo -n "$dot"
    sleep 1.5s
  done 
  echo
}

# Disable splunk at start up
{
  echo "START: `date`"
  echo "Disable splunk at boot time"
  # Is it systemd or system V init?
  # Disable splunk at start up
  cd /etc/init.d && {
     [[ -f splunk ]] && {
           mv -f splunk Splunk
           chkconfig splunk off
     }
  }
  cd /etc/systemd/system && {
     [[ -f Splunkd.service ]] && systemctl disable Splunkd
     sleep 30s
     # Verify symlink is no longer there.
     [[ -L /etc/systemd/system/multi-user.target.wants/Splunkd.service ]] && {
       echo "Symlink /etc/systemd/system/multi-user.target.wants/Splunkd.service is still there. Abort"
       echo "Run systemctl disable Splunkd"
       exit
     }
  }
  echo
  echo "IMPORTANT: Please wait until the command line prompt is back."
  echo "           `uname -n` is reassigning its buckets to its peers in the cluster."
  {
    eval `gpg --batch --xyz xyz -quiet --no-verbose -d /.splunk` >/dev/null 2>&1
  } 2>/dev/null
  case ${env_} in
   pdv | bdv ) uid=ser_act.dev
               key=${dev}
               ;;
   some_loc | loc2 | loc3 | loc4 ) uid=ser_act.prod
                           key=${prod}
               ;;
           * )
               case `uname -n` in
                         ser2* ) uid=ser_act.prod
                                gid=unx_9998_access
                                key=${prod}
                                ;;
                   cud*| cut* ) uid=ser_act.dev
                                gid=unx_60231_splunk_admin_dev
                                key=${dev}
                                ;;
               esac
               ;;
  esac
  echo
  su - ${uid} -c "/opt/splunk/bin/splunk offline -auth admin:${key}"
  # Make sure Splunkd not respawning
  wait_5s
  echo
  echo "`date`: Verify if splunkd is down" 
  echo
  # verify if splunkd is down
  pgrep -u ${uid} splunkd >/dev/null 2>&1
  [[ "$?" = "0" ]] && {
     echo "Stopping splunkd via Splunkd.service"
     systemctl stop Splunkd
     echo "splunkd is killed. splunk_offline completed."
     # Verify again
     sleep 2s
     pgrep -u ${uid} splunkd >/dev/null 2>&1
     [[ "$?" = "0" ]] && {
         echo "Final Kill splunkd"
         pgrep -u ${uid} splunkd |xargs kill -9
     }
  }
  echo
  echo "END of $0 : `date`"
  echo
  echo "This Indexer, `uname -n`, is ready for maintenance/OS Patching work."
  echo
  cat<<END
      ################## ATTENTION ATTENTION ATTENTION ###############
      #      Once Patching or Maintenance Completed, please run      #
      #                                                              #
      #                      re-enable_splunk                        #
      ################################################################

END
}| tee /var/tmp/`basename $0`.${date_}.OUT.$$

mailx -s "splunk_offline output|`uname -n`:/var/tmp/`basename $0`.${date_}.OUT.$$" ${TOS_splunk_team} < /var/tmp/`basename $0`.${date_}.OUT.$$
systemctl daemon-reload
