#!/bin/bash
###################################################################################
# This to provide SPlunk admin access to standalone search head or search head
# cluster url once servers configured with iDP/SAML SSO.
###################################################################################
# user_ | T O S Platform Splunk
{
eval `gpg --batch --xyz xyz -quiet --no-verbose -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

check_env ()
{
  nslookup $name | grep 'canonical'|grep 'dev.mycorp.com' >/dev/null
  if [[ "$?" = "0" ]]
  then
    key=${dev}
  else
    nslookup $name |grep 'dev.mycorp.com' >/dev/null
    if [[ "$?" = "0" ]]
    then
      key=${dev}
    else
      key=${prod}
    fi
  fi
}

check_F5 ()
{
  # is it F5 LB?
  nslookup $name | grep 'canonical'|grep 'igslb'  >/dev/null
  if [[ "$?" = "0" ]]
  then
   output_="https://${name}/en-US/account/login?loginType=splunk"
  else
   output_="https://${name}:8000/en-US/account/insecurelogin?loginType=splunk&username=admin&password=${key}"
  fi
}

##########
# M A I N
##########
echo -n "Enter [ hostname | DNS CNAME | F5 LB ] with FQDN? "
read name
# Is it in DNS?
nslookup $name | grep 'canonical' >/dev/null
if [[ "$?" = "0" ]]
then
  # Is it DEV/PROD
  check_env
  # is it F5 LB?
  check_F5 
else
  nslookup $name | grep '^Name' >/dev/null
  if [[ "$?" = "0" ]]
  then
    check_env 
    check_F5 
  else
    echo "${name} is NOT in DNS"
    exit
  fi
fi

cat<<END
Cut/paste below in IE/Chrome:

${output_}

END

