#!/bin/ksh
env_=`uname -n|grep -o '...$'`

case ${env_} in
   loc2 )
        kafka=kafka-topic-loc2-geneos-raw.table
        ;;
   some_loc )
        kafka=kafka-topic-some_loc-geneos-raw.table
        ;;
esac

curl -X DELETE --insecure https://`uname -n`:8443/connectors/${kafka}

