#!/bin/bash
echo -n "Enter Window AD login first.last? "
read user_name

# Check first.last on ser10934some_loc:/bitbucket/user2
check_username=`{
cat<<END | ssh ser10934some_loc 2>/dev/null
[[ -d /bitbucket/${user_name} ]] && echo "0"
END
}`

echo check_username=$check_username
