#!/bin/ksh
# Run this from mycorp Control servers
# sourcetype = itrs_json
# token = afb859db-1499-4536-b2be-497aef1e8e6c
#curl -k https://${hec}.some_loc.mycorp.com:8088/services/collector -H 'Authorization: Splunk afb859db-1499-4536-b2be-497aef1e8e6c' -d ' {"sourcetype": "itrs_json", "event":"Testitrs_json! Testitrs_json! Testitrs_json!"}'

# source type = thousandeyes
# token = 0a3d6a83-349b-4a1d-aab8-a1bdb97c48f4
#curl -k https://${hec}.some_loc.mycorp.com:8088/services/collector -H 'Authorization: Splunk 0a3d6a83-349b-4a1d-aab8-a1bdb97c48f4' -d ' {"sourcetype": "thousandeyes", "event":"Test_TE! Test_TE! Test_TE!"}'
#token='0a3d6a83-349b-4a1d-aab8-a1bdb97c48f4'
#token='b6b14c8b-3255-41d3-9a18-f53ba100df64'
token='7c49808e-389c-4d38-8cc6-33841e75c709'
hec=ser24-007714.us.global.mycorp.com
curl -k https://${hec}:8088/services/collector -H 'Authorization: Splunk ${token}' -d ' {"sourcetype": "pcf_test", "event":"Test_TE! Test_TE! Test_TE!"}'
