#!/bin/ksh
###############################################################################
# This script transfer captaincy from one peer to another within its search 
# head cluster.
# The procedure is based on
# https://docs.splunk.com/Documentation/Splunk/8.1.5/DistSearch/Transfercaptain#Transfer_captaincy
#
# user_ | T O S
###############################################################################
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

case ${env_} in
         pdv | bdv )
                     uid=ser_act.dev
                     gid=unx_60231_splunk_admin_dev
                     key=$dev
                     ;;
   some_loc | loc2 | loc3 | loc4 ) 
                     uid=ser_act.prod
                     gid=unx_9998_access
                     key=$prod
                     ;;
                 * )
                     case `uname -n` in
                           ser2* )
                                uid=ser_act.prod
                                gid=unx_9998_access
                                key=$prod
                                ;;
                            cud*| cut* )
                                uid=ser_act.dev
                                gid=unx_60231_splunk_admin_dev
                                key=$dev
                                ;;
                     esac
                     ;;
esac

[[ "`whoami`" != "${uid}" ]] && {
  echo "This script runs as ${uid} only. Abort."
  exit
}

${SPLUNK_BIN}/splunk login -auth admin:${key}
# Get a list of all Search peers
echo "Below is list of search peers in the cluster"
peers=$(${SPLUNK_BIN}/splunk list shcluster-members|grep label|sed -e 's/^[ \t]*//' -e 's/label://g')
echo $peers

# Identify captain
captain=$(${SPLUNK_BIN}/splunk list shcluster-members -auth|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}')
echo "Captain: $captain"

echo
echo -n "Transfer current captain, $captain, to another search peer (Y|N)? "
read ans
case $ans in
  Y|y )
       echo -n "Enter search peer hostname? "
       read peer
       # Get url instead of SH nodename.  
       peer_url=$(${SPLUNK_BIN}/splunk list shcluster-members|grep 'mgmt_uri:'|awk -F: '{printf"%s:%s:%s\n",$2,$3,$4}'|grep ${peer})
       echo ${peer_url}|grep "$peer" > /dev/null
       if [[ "$?" = "0" ]]
       then
          echo "Switch captaincy to $peer"
          # Check its hostname
          #${SPLUNK_BIN}/splunk transfer shcluster-captain -mgmt_uri https://${peer}:8089 >/dev/null
          ${SPLUNK_BIN}/splunk transfer shcluster-captain -mgmt_uri ${peer_url}
          echo
          echo "Checking for new captain...."   
          sleep 3
          new_captain=$(${SPLUNK_BIN}/splunk list shcluster-members -auth|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}')
          echo "New captain: ${new_captain}"
       else
          echo "${peer} is not shown in Search Head cluster:"
          echo ${peers}
          echo
          exit
       fi
       ;;
    * )
       echo "Unexpected input. Abort."
       exit
       ;;
esac
