#!/bin/bash
# Splitting up splunk.mycorp.com's [E|F]-core into adhoc 
# Add the following to server.conf's [shclustering] stanza
# [shclustering]
# adhoc_searchhead = true
#
# Scheduled – splunk.mycorp.com.  9/26 – these will actually be the ad hoc only.
# RC to modify F5 : 2183772
#
# ser14428some_loc	10.102.173.20 	E-core
# ser14343some_loc	10.102.173.21 	E-core
# ser14344some_loc	10.102.173.22 	E-core
# ser14350some_loc	10.102.189.86 	F-core
# ser14351some_loc	10.102.189.87 	F-core
# ser14352some_loc	10.102.189.88 	F-core
# ser14343loc2	10.106.173.21 	E-core
# ser14344loc2	10.106.173.22 	E-core
# ser14350loc2	10.106.189.86 	F-core
# ser14351loc2	10.106.189.87 	F-core
# ser14352loc2	10.106.189.88 	F-core
#
# http://docs.splunk.com/Documentation/Splunk/6.6.3/DistSearch/Adhocclustermember

SPLUNK_LOCAL=/opt/splunk/etc/system/local

cd ${SPLUNK_LOCAL} && {
  [[ -f server.conf ]] && {
    grep '^adhoc_searchhead' server.conf > /dev/null
    [[ "$?" != "0" ]] && sed -i '/\[shclustering/aadhoc_searchhead = true' server.conf 
  }
}
