#!/bin/bash

verify_SplunkForwarder_service_at_boot ()
{
  cd /etc/systemd/system && {
     splunkUF_service=`ls |grep -i splunkforwarder.service`
     [[ -f ${splunkUF_service} ]] && {
           echo "In /etc/systemd/system, rename ${splunkUF_service} to SplunkForwarder.service"
           mv -f ${splunkUF_service} SplunkForwarder.service
           echo "Enable splunkUF@boot"
           systemctl enable SplunkForwarder.service
     }
  }
}

verify_SplunkForwarder_service_at_boot
echo "Stopping SplunkUF"
pgrep splunkd|xargs kill
echo
echo "Starting SplunkUF"
systemctl start SplunkForwarder
echo "Verifying splunkUF"
pgrep splunkd
