#!/bin/bash
kill_jid ()
{
  curl --location --request POST 'https://cmaapidomain1/salt/kill_running_job' \
       --header "X-Auth-Key: ${X_Auth_Key}" \
       --header "X-Auth-Token: ${X_Auth_Token}" \
       --header 'Content-Type: application/json' \
       --data '[{
                  "target": "some_loc11-012458",
                  "jid": "'"${jid}"'",
                  "tgt_type": "grain"
               }]'
}

jid=$1
kill_jid 
