#!/bin/bash

if [[ $# = "0" ]]
then
   echo "List of apps in $(uname -n):/root/W2K_INDEX_MIGRATION"
   echo
   ls /root/W2K_INDEX_MIGRATION
   echo
   read -p "Enter Indexer app name? " indexer_app
   echo 
else
   indexer_app=$1
fi
  

{
  cd /root/W2K_INDEX_MIGRATION/$indexer_app && {
    for w2k in $(cat ${indexer_app}.list)
    do
      echo "${w2k}:"
      win_uf_checks prod ${w2k}|grep -q ERROR
      if [[ "$?" = "0" ]]
      then
         win_uf_checks prod ${w2k}|grep ERROR
      else
         {
           win_uf_checks prod ${w2k}
         } |awk -F"failed" '/^WARNING/{printf"%sfailed\n",$1}'
      fi
    done
  }
} | tee /root/W2K_INDEX_MIGRATION/$indexer_app/${indexer_app}.result

echo "OUTPUT:  /root/W2K_INDEX_MIGRATION/$indexer_app/${indexer_app}.result"

