#!/bin/ksh
###################################################################################
# This script is based on https://jiradomain1/browse/TOS-12813
# ReBalance PDC1/3 Index buckets
# According to 
# https://docs.splunk.com/Documentation/Splunk/7.2.6/Indexer/ \
#       Rebalancethecluster#Initiate_data_rebalancing
# The tasks are performed on Splunk Index Cluster Master, ser10859some_loc
# As service service account ser_act.[prod|dev],
# - To initiate bucket rebalance 
# ${SPLUNK_BIN}/splunk cluster-data -action start [-max_runtime interval_in_minutes]
# - To stop
# ${SPLUNK_BIN}/splunk cluster-data -action stop
# - To check on stattus
# ${SPLUNK_BIN}/splunk cluster-data -action status
# 
# The script gathers indexer's total bucket counts, sort by its logical site
# then provide cluster rebalancing status (in % complete)
# Output:
# LOG=/tmp/BUCKET_REBALANCE/get_bucket_counts.${YYYY}-${MM}.${DD}_${HH}${MM}.log
###################################################################################
# Written by user1 user1 | TOS Platform Splunk
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
date_=$(date '+%F_%H%M')
LOG=/tmp/BUCKET_REBALANCE
[[ ! -d ${LOG} ]] && mkdir -p ${LOG}
{
  eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

case ${env_} in
   pdv | bdv ) uid=svc_act2
               gid=unx_60231_splunk_admin_dev
               key=${dev}
               ;;
   some_loc | loc2 ) uid=svc_act1
               gid=unx_9998_access
               key=${prod}
               ;;
esac
{
  {
    #su - ${uid} -c "${SPLUNK_BIN}/splunk show cluster-status --verbose -auth admin:${key}" | \
    #   egrep -A3 'some_loc|loc2'|grep -v '\-\-'|egrep -v 'Searchable|Status' | \
    su - ${uid} -c "${SPLUNK_BIN}/splunk show cluster-status -auth admin:${key}" | \
    egrep 'site|Bucket' | \
    while read line
    do
      echo "$line"|grep 'site' >/dev/null
      if [[ "$?"  = "0" ]]
      then
        echo -n "$line "
      else
        echo "$line "|grep 'Bucket' >/dev/null
        [[ "$?"  = "0" ]] && echo $line
      fi
    done
  } | sort -k3
  echo
  date
  su - ${uid} -c "${SPLUNK_BIN}/splunk rebalance cluster-data -action status"
} | tee  ${LOG}/`basename $0`.${date_}.log
