#!/bin/ksh
###################################################################################
# This script runs on Splunk Index Cluster Master and checks for conditions below
# to ensure it's healthiness.
#
# Pre-flight check successful .................. YES
# ├────── Site replication factor met .......... YES
# ├────── Site search factor met ............... YES
# ├────── All data is searchable ............... YES
#
# Outputs:
# . GOOD
#   All conditions are YES
# . BAD
#   Any of the conditions above is not met.
###################################################################################
# user1 P user1 | TOS Platform Splunk
SPLUNK_BIN=/opt/splunk/bin
# Store lines in array array_line
set -A array_line $line
set -A array_value $value
line_=""
num=0
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

if [[ "$1" = "-v" ]]
then
    su - svc_act1 -c "${SPLUNK_BIN}/splunk show cluster-status --verbose -auth admin:${prod}"
else  
   {
     su - svc_act1 -c "${SPLUNK_BIN}/splunk show cluster-status --verbose -auth admin:${prod}"|grep -A3 'Pre-flight check successful'
   } | while read line
       do
         array_line[${num}]=`echo $line`
         echo ${array_line[${num}]} |grep 'YES' >/dev/null 2>&1
         [[ "$?" = "0" ]] && array_value[${num}]=`echo $line|awk '{print $NF}'`
         num=`expr $num + 1`
       done
   
#  echo array_value_count=${#array_value[@]}
#  array_value[0]=YES
#  array_value[1]=YES
#  array_value[2]=YES
#  array_value[3]=GERRY

   # Build array string: 
   k=0
   l=0
   get_array ()
   {
     for i in ${array_value[*]}
     do
        echo -n '[[ "${array_value['
        echo -n $k
        echo -n ']}"'
        #echo -n ' != '
        echo -n ' = '
        #echo -n '"YES'
        echo -n '"'
        echo -n ${array_value[$l]}
        [[ $k -lt 3 ]] && echo -n '" ]] && ' 
        k=`expr $k + 1`
        l=`expr $l + 1`
     done
     echo '" ]]'
    }

    array_=`get_array`
#echo array_=$array_
#echo "`eval ${array_}`"

    #if eval "[[ ${array_} ]]"
    #if [[ "${array_value[0]}" = "YES" ]] && [[ "${array_value[1]}" = "YES" ]] && [[ "${array_value[2]}" = "YES" ]] && [[ "${array_value[3]}" = "YES" ]]
    if [[ "${array_value[1]}" = "YES" ]] && [[ "${array_value[2]}" = "YES" ]] && [[ "${array_value[3]}" = "YES" ]]
    then
      echo "GOOD"
    else
      echo "BAD"
      for num in {0..3}
      do
        echo ${array_line[${num}]}
      done
    fi
fi

