#!/bin/ksh
# Splunk Service account:
#svc_act1:VAS:500327:9998:svc_act1:/svc_act1:/bin/ksh
#svc_act2:VAS:562314:60231:svc_act2:/svc_act2:/bin/ksh
env_=`uname -n`
typeset -R3 env_

case ${env_} in
   pdv | bdv ) UID=svc_act2
               ;;
   some_loc | loc2 ) UID=svc_act1
               ;;
esac
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null
su - ${UID} -c "/opt/splunk/bin/splunk login -auth admin:${prod};/opt/splunk/bin/splunk enable maintenance-mode"

