#!/bin/ksh
###################################################################################
# This script is based on https://jiradomain1/browse/TOS-12813
# ReBalance PDC1/3 Index buckets
# According to 
# https://docs.splunk.com/Documentation/Splunk/7.2.6/Indexer/ \
#       Rebalancethecluster#Initiate_data_rebalancing
# The tasks are performed on Splunk Index Cluster Master, ser10859some_loc
# As service service account ser_act.[prod|dev],
# - To initiate bucket rebalance 
# ${SPLUNK_BIN}/splunk cluster-data -action start [-max_runtime interval_in_minutes]
# - To stop
# ${SPLUNK_BIN}/splunk cluster-data -action stop
# - To check on stattus
# ${SPLUNK_BIN}/splunk cluster-data -action status
###################################################################################
# Written by user1 user1 | TOS Platform Splunk
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
{
  eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

case ${env_} in
   pdv | bdv ) uid=svc_act2
               gid=unx_60231_splunk_admin_dev
               key=${dev}
               ;;
   some_loc | loc2 ) uid=svc_act1
               gid=unx_9998_access
               key=${prod}
               ;;
esac

su - ${uid} -c "${SPLUNK_BIN}/splunk rebalance cluster-data -action stop -auth admin:${key}"
