#!/bin/bash
##############################################################################
# This script adds new search head into search head cluster,
# https://splunkdomain1
# Once new search head is initialized, ${SPLUNK_LOCAL}/server.conf's stanza,
# [shclustering], the followings will be added 
# - If search head is adhoc,
#   conf_replication_include.passwd = true
#   captain_is_adhoc_searchhead = true
#   adhoc_searchhead = true
# - If search head is regular or none
#   conf_replication_include.passwd = true
#   captain_is_adhoc_searchhead = true
##############################################################################
# Written by user1 user1 | TOS Splunk Platform
node=`uname -n`
node_fqdn=$(host $node|awk '{print $1}')
SPLUNK_LOCAL=/opt/splunk/etc/system/local
SPLUNK_BIN=/opt/splunk/bin
date_=$(date '+%a%H%M_%m%d%Y')
env_=`uname -n|grep -o '...$'`
bold_yellow="\e[1m\e[33m"
green=$(tput setaf 2)
red=$(tput setaf 1)
reset_color="\e[0m"

set_env ()
{
   case ${env__} in
        PR|pr|pR|Pr )
                      F5_fqdn=splunk-preproddomain1
                      SH_Deployer=ser10982some_loc.some_locdomain1
                      secret=preprodcluster
                      shcluster_label=preprod_shcluster
                      option=none
                      ;;
                P|p )
                      F5_fqdn=splunkdomain1
                      SH_Deployer=splunkdeployerdomain1
                      secret=prodcluster
                      shcluster_label=prod_shcluster
                      echo -en "Is ${node} [${bold_yellow}A${reset_color}]dhoc, or [${bold_yellow}N${reset_color}]one? "
                      read ans
                      case ${ans} in
                            A|a ) option=adhoc
                                  ;;
                            N|n ) option=none
                                  ;;
                      esac
                      ;;
                E|e )
                      F5_fqdn=splunk-esdomain1
                      SH_Deployer=splunkdeployerdomain1
                      secret=prodcluster
                      shcluster_label=prod-es_shcluster
                      option=none
                      ;;
                I|i )
                      F5_fqdn=splunk-itsidomain1
                      SH_Deployer=splunkdeployer-itsidomain1
                      secret=prodcluster
                      shcluster_label=prod-itsi_shcluster
                      option=none
                      ;;
                X|x )
                      F5_fqdn=splunk-extractsdomain1
                      SH_Deployer=ser10983some_loc.some_locdomain1
                      secret=weblogs_shcluster
                      shcluster_label=weblogs_shcluster
                      option=none
                      ;;
                  * )
                      echo -en "Enter ${bold_yellow}PR${reset_color}, ${bold_yellow}P${reset_color},${bold_yellow}E|I|X${reset_color}. Try again."
                      exit
                      ;;
   esac
}

{
eval `gpg --batch --xyz xyz -quiet --no-verbose -d /.splunk` >/dev/null 2>&1
} 2>/dev/null


# Service Account only.
case ${env_} in
   pdv | bdv ) uid=svc_act2
               key=${dev}
               ;;
   some_loc | loc2 | loc3 |loc4  ) uid=svc_act1
                           key=${prod}
               ;;
           * )
               case `uname -n` in
                        some_loc11* | some_loc14* | some_loc17* ) uid=svc_act1
                                                key=${prod}
                                                ;;
                        cud*| cut* ) uid=svc_act2
                                     key=${dev}
                                     ;;
               esac
               ;;
esac

if [[ "`whoami`" != "${uid}" ]]
then
   echo "Running `basename $0` as ${uid} only. Abort."
   exit
fi

echo "Initializing Search Head $node to Search Head Cluster."

echo -en "Is it [${bold_yellow}PR${reset_color}]e-Prod, [${bold_yellow}P${reset_color}]ROD, [${bold_yellow}E${reset_color}]S, or [${bold_yellow}I${reset_color}]TSI, or WebLog E[${bold_yellow}X${reset_color}]tract Search Head? "
read env__
set_env
captain=`curl -k -u admin:${key} https://${F5_fqdn}:8089/services/shcluster/captain/info 2>/dev/null|grep "label"| awk -F'>' '{print $2}'|sed 's/<\/s:key//g'`

{
# Initialize the instance
grep '^\[shclustering' ${SPLUNK_LOCAL}/server.conf >/dev/null
if [[ "$?" != "0" ]]
then
   echo "Initializing $node as option ${option} instance"
   ${SPLUNK_BIN}/splunk login -auth admin:${prod}
   ${SPLUNK_BIN}/splunk init shcluster-config -mgmt_uri https://${node_fqdn}:8089 -replication_port 9886 -replication_factor 3 -conf_deploy_fetch_url https://${SH_Deployer}:8089 -secret ${secret} -shcluster_label ${shcluster_label}
fi


case ${option} in
     adhoc )
            cat<<END

Add the followings to ${SPLUNK_LOCAL}/server.conf [shclustering] stanza:

conf_replication_include.passwd = true
captain_is_adhoc_searchhead = true
adhoc_searchhead = true

AND

[httpServer]
maxSockets = 262144
maxThreads = 131072

END
            sed -i 's/\[shclustering\]/&\nconf_replication_include.passwd = true\ncaptain_is_adhoc_searchhead = true\nadhoc_searchhead = true/' ${SPLUNK_LOCAL}/server.conf
            sed -i '$a\\n\[httpServer\]\nmaxSockets = 262144\n\maxThreads = 131072\n' ${SPLUNK_LOCAL}/server.conf
            ;;
      none )
            cat<<END

Add the followings to ${SPLUNK_LOCAL}/server.conf [shclustering] stanza:

conf_replication_include.passwd = true
captain_is_adhoc_searchhead = true

AND

[httpServer]
maxSockets = 262144
maxThreads = 131072

END
            sed -i 's/\[shclustering\]/&\nconf_replication_include.passwd = true\ncaptain_is_adhoc_searchhead = true/' ${SPLUNK_LOCAL}/server.conf
            sed -i '$a\\n\[httpServer\]\nmaxSockets = 262144\n\maxThreads = 131072\n' ${SPLUNK_LOCAL}/server.conf
            ;;
        * )
            echo "option either Adhoc OR None. Abort."
            exit
esac

echo "Now restarting splunk check kvstore via: /opt/splunk/bin/splunk show kvstore-status as ${uid}" 

echo "Next step, as ${uid} on ${F5_fqdn} Search Head captain, ${captain}, run "
echo "${SPLUNK_BIN}/splunk add shcluster-member -new_member_uri https://${node_fqdn}:8089 -auth admin:admin_key"
} | tee /${uid}/`basename $0`.${date_}.OUT
echo
echo "OUTPUT: /${uid}/`basename $0`.${date_}.OUT"
