#!/bin/ksh
###############################################################################
# This script transfer captaincy from one peer to another within its search 
# head cluster.
# The procedure is based on
# https://docs.splunk.com/Documentation/Splunk/7.2.4/DistSearch/Transfercaptain#Transfer_captaincy
#
# user_ | T O S
###############################################################################
SPLUNK_BIN=/opt/splunk/bin
env_=`uname -n|grep -o '...$'`
{
eval `gpg --batch --xyz xyz -d /.splunk` >/dev/null 2>&1
} 2>/dev/null

case ${env_} in
         pdv | bdv )
                     uid=svc_act2
                     gid=unx_60231_splunk_admin_dev
                     fqdn="devdomain1"
                     key=$dev
                     ;;
   some_loc | loc2 | loc3 ) 
                     uid=svc_act1
                     gid=unx_9998_access
                     fqdn="some_locdomain1"
                     key=$prod
                     ;;
                 * )
                     case `uname -n` in
                           some_loc1* )
                                uid=svc_act1
                                gid=unx_9998_access
                                fqdn="us.globaldomain1"
                                key=$prod
                                ;;
                            cud*| cut* )
                                uid=svc_act2
                                gid=unx_60231_splunk_admin_dev
                                fqdn="us.globaldomain1"
                                key=$dev
                                ;;
                     esac
                     ;;
esac

[[ "`whoami`" != "${uid}" ]] && {
  echo "This script runs as ${uid} only. Abort."
  exit
}

${SPLUNK_BIN}/splunk login -auth admin:${key}
# Get a list of all Search peers
echo "Below is list of search peers in the cluster"
peers=$(${SPLUNK_BIN}/splunk list shcluster-members|grep label|sed -e 's/^[ \t]*//' -e 's/label://g')
echo $peers

# Identify captain
captain=$(${SPLUNK_BIN}/splunk list shcluster-members -auth|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}')
echo "Captain: $captain"

echo
echo -n "Transfer current captain, $captain, to another search peer (Y|N)? "
read ans
case $ans in
  Y|y )
       echo -n "Enter search peer hostname? "
       read peer
       echo ${peers}|grep "$peer" > /dev/null
       if [[ "$?" = "0" ]]
       then
          echo "Switch captaincy to $peer"
          # Check its hostname
          ${SPLUNK_BIN}/splunk transfer shcluster-captain -mgmt_uri https://${peer}.${fqdn}:8089 >/dev/null
          echo
          echo "Checking for new captain...."   
          sleep 3
          new_captain=$(${SPLUNK_BIN}/splunk list shcluster-members -auth|grep -A1 'is_captain:1'|tail -1|awk -F: '{print $2}')
          echo "New captain: ${new_captain}"
       else
          echo "${peer} is not shown in Search Head cluster:"
          echo ${peers}
          echo
          exit
       fi
       ;;
    * )
       echo "Unexpected input. Abort."
       exit
       ;;
esac
